### ISSUE TITLE
DWD Neu FTP-Pfade und Dateinamen. 

### ISSUE THREAD

**Issue by grisuv** [ioBroker/ioBroker.dwd#1]
Hallo,

DWD wird die FTP Pfade und Dateinamen ändern. ab Jahresende 2015  wird der jetzige abruf nicht mehr funktionieren.
Eine Anpassung der jetzt schon vorhandenen Pfade ist notwendig.

Bei mir werden jetzt schon keine Warnungen mehr ausgegeben

siehe Mails vom DWD:

Sehr geehrte GDS-Nutzer,

zur Erinnerung und weiteren Konkretisierung der angekündigten und unmittelbar bevorstehenden Änderungen in den Warnprodukten des DWD erhalten Sie mit diesem Newsletter noch einmal eine Zusammenfassung der
zeitlichen Abfolge und weitere Details zu den Umstellungen. Da sich sowohl die Verzeichnisstruktur und Dateinamen, also auch Dateiinhalte ändern, raten wir dringend Ihre Anschlussprozesse UMGEHEND an die Umstellungen anzupassen!

Termin 06.10.2015:
==================
Neue Verzeichnisstruktur /gds/specials/alerts ist eingerichtet, Testfiles mit neuen Dateinamen und –inhalten sind verfügbar. Bitte machen Sie sich ZEITNAH mit der neuen Struktur vertraut:

- /gds/specials/alerts/cap/GER/ : Gesamt-CAP-Dateien Deutschland in den Unterverzeichnissen: status, status_geometry, difference
Beachten Sie bitte die neuen Dateinamen: Z_CAP_C_EDZW_YYYYMMDDhhmmss_PVW_*.zip und neue Inhalte wie z.B. geänderte WarnCell-IDs (siehe GDS-newsletter vom 25.09.2015)
Hinweis: xml-Dateien als zip-Files komprimiert, gleichartige Warnungen in einer xml, z.B. auch Küstenwarnungen explizit

- /gds/specials/alerts/cap/EM/  [… HA, LZ, MS, OF, PD, SU]: Einzel-CAP-Dateien für die Regionen: EM, HA, LZ, MS, OF, PD, SU
Beachten Sie bitte die neuen Dateinamen: Z_CAP_C_EDZW_YYYYMMDDhhmmss_PVW_*.xml und neue Inhalte wie z.B. geänderte WarnCell-IDs (siehe GDS-newsletter vom 25.09.2015)

Zusätzlich auch Warnungen für Küstenregionen (Nord-/Ostsee) und Binnenseen, siehe auch Dokumentation in /gds/help/legend_warnings.xls, Register „Regionen“, Warncell-IDs mit blauer Schrift in Spalte M.

- /gds/specials/alerts/sms/: SMS-Texte für die Regionen: EM, HA, LZ, MS, OF, PD, SU
Beachten Sie bitte die kleineren Anpassungen der SMS-Texte, siehe auch Dokumentation in /gds/help/legend_warnings.xls, Register „SMS_Warnungen_Standard_Details“, blaue Schrift

- /gds/specials/alerts/txt/: Warnlageberichte / Unwetterwarnungen für die Regionen: EM, HA, LZ, MS, OF, PD, SU und GER (hier nur Warnlage D und Wochenvorhersage Wettergefahren D sowie Medieninfo Unwetter)

- /gds/specials/alerts/maps/: Kartendarstellung der Warnlage (entspricht bisherigen Inhalten unter /gds/specials/warnings/maps/)

- /gds/specials/alerts/health/: Biowetter, Pollenvorhersage etc. (entspricht bisherigen Inhalten unter /gds/specials/warnings/FG/)

Termin 13.10.2015:
==================
Die neue Verzeichnisstruktur /gds/specials/alerts/ wird OPERATIONELL beliefert.

Daher wird die Bereitstellung der bisherigen Gesamt-CAP-Dateien unter /gds/specials/warnings/xml/PVW/ und /gds/specials/alerts/DL/ EINGESTELLT!!!

Termin 20.10.2015:
==================
Die Bereitstellung der Einzel-CAP-Dateien unter /gds/special/warnings/xml/EM/  [… HA, LZ, MS, OF, PD, SU] wird EINGESTELLT!!!

Die Belieferung der noch verbleibenden Verzeichnisse: /gds/special/warnings/DL [EM, HA, LZ, MS, OF, PD, SU, sms, maps, FG] wird voraussichtlich zum Ende des Jahres 2015 EINGESTELLT!!!

Weitere Informationen entnehmen Sie bitte den newslettern vom 18. und 25.09.2015. sowie der Komplettübersicht (Datei „legend_basic_service_level.xls“ - gelb markierte Felder) unter /gds/help auf Ihrem FTP-Account.

Insbesondere die Termine 13. und 20.10.2015 sind vorbehaltlich zu verstehen, da z.B. eine schwere Unwetterlage zu einer Verschiebung führen kann.

Zur Umstellung auf synoptische BUFR-Daten bieten wir ihnen weitere Informationen FM 94 BUFR-Synop für den nationalen und internationalen Teil an, sie finden sie im Verzeichnis gds/help unter legend_BUFR-Synop_Template_D.pdf und legend_BUFR-Synop_Template_INT.pdf.

Freundliche Grüße von Ihrem
GDS-Team (gds.admin@dwd.de)

------------------------ Zweite Mail---------------------------------

Sehr geehrte Nutzer des GDS,

auf Wunsch zahlreicher Kunden werden wir die angekündigten Umstellungen im Warnmanagement schrittweise, mit teilweise parallelen Lieferungen durchführen. Daher – und zur Konkretisierung einiger Punkte - erhalten Sie heute dieses Update unseres GDS-Newsletters vom 18.09.2015:

--------------------------------------------------------------------------

SCHRITTWEISE Umstellungen im Warnmanagement des DWD zwischen dem 06.10.2015 und voraussichtlich 20.10.2015

Der Deutsche Wetterdienst entwickelt und verbessert sein Warnmanagement kontinuierlich, und in diesem Zusammenhang wird es in Kürze deutliche Erweiterungen und Umstellungen geben. Die Änderungen werden ermöglicht durch optimierte Produktionsprozesse im nationalen Warnzentrum des DWD und die zunehmende Möglichkeit, Warnungen über das Internet und in Apps mit höheren zeitlichen Aktualisierungsraten anzubieten. Zentraler Aspekt der Umstellung wird die Einführung von zwei parallelen Produktschienen sein, den sogenannten Standard- und Premium-Warnungen. Alles Wesentliche ist in gds/help/legend_warnings.xls dokumentiert.

Die unten näher beschriebenen neuen Produkte werden im gds unterhalb der Verzeichnisstruktur /gds/specials/alerts abgelegt.

!!!!! A C H T U N G !!!!!
Die Lieferung aller bisherigen Produkte im gewohnten Format unter /gds/specials/warnings kann voraussichtlich ab 13.10.2015 nicht mehr gewährleistet werden! Deshalb raten wir DRINGEND allen Nutzern ihre Prozesse ab 06.10.2015 sukzessive auf die neuen Produkte unter der neuen Verzeichnisstruktur /gds/specials/alerts umzustellen!

Wesentliche Merkmale und Änderungen der beiden neuen Produktschienen sind im Folgenden beschrieben.

Standard-Warnungen:
===================
Dieses Produkt entspricht größtenteils den gewohnten bisher ausgegebenen einzelnen Text-Warnungen. Auf den Standard-Warnungen beruhen auch weiterhin unsere SMS-, FAX- und Newsletterverteilungen.

Angebotene Warngebiete: Landkreise, Regionen, Binnenseen, Regierungsbezirke, Länder und Sondergebiete wie z.B. Norddeutschland

Angebotene Formate:

- TXT -> jeweiliges Unterverzeichnis unter /gds/specials/alerts/txt/EM /HA /LZ /MS /OF /PD /SU

- SMS-TXT -> jeweiliges Unterverzeichnis unter /gds/specials/alerts/sms/EM…SU

- Einzel-CAP -> jeweiliges Unterverzeichnis unter /gds/specials/alerts/cap/EM…SU

!! A C H T U N G !!
Ab voraussichtlich 20.10.2015 wird sich die interne Dateistruktur der Einzel-CAP-files ändern. Beispiele zum Vergleich der neuen und bisherigen Struktur finden Sie unter gds/help als
ALT: legend_example_Z_CAP*OMEDES* -> weniger umfangreich u.a. inkl. CellIDs
NEU: legend_example_Z_CAP*PVW* -> umfangreicher u.a. inkl. WarnCellIDs (Spalte M) etc., dafür entfallen CellIDs (Spalte L) in legend_warnings.xls, Register „Regionen“
Wir raten DRINGEND!!! Ihre Prozesse auf diese neue Struktur anzupassen, da nach der Umstellung die alten Einzel-CAP-files nicht mehr bzw. nur im Backup-Fall zur Verfügung stehen werden!

Inhaltliche Unterschiede zum derzeitigen Warnprodukt:
1. Frostwarnung WW81 entfällt, dafür wird die Frostwarnung WW22 ganzjährig ausgegeben (siehe legend_warnings.xls, Register „Warnungen_Standard_Details“)

2. Für die Standardwarnungen werden die bisherigen Gewitterwarnungen in vier Klassen zusammengefasst (90-93, siehe legend_warnings.xls, Register „Warnungen_Standard_Details“). Da im Backup-Fall die bisherigen Gewitter 30…49 bzw. 94…96 noch vorkommen können, empfehlen wir die 90…93 parallel einzurichten.

3. Im Text wird  das Ende des Gültigkeitszeitraums mit „bis voraussichtlich“ statt „bis“ angegeben. Grund dafür ist die Kundenanforderung, nach einem Warnprodukt mit weniger häufigen Aktualisierungsraten. Für hochaktuelle Warninformationen wird im Text auf www.wettergefahren.de <http://www.wettergefahren.de> hingewiesen.

4. Unter Regionen wurde ein Gebiet in Mecklenburg-Vorpommern geändert, MVO (Mecklenburg-Vorpommern Ost) statt VOP (Vorpommern)

Premium-Warnungen:
==================
Dieses Produkt wird als CAP-file zur Verfügung gestellt. Die Auslieferung ist hochaktuell (2-10 Minuten), sodass es sich nicht für Einzelbelieferungen eignet sondern für Visualisierungssysteme und Datenverteilung wie z.B. für unsere WarnWetter-App und unseren zukünftigen Internetauftritt.

Angebotene Warngebiete: Zunächst Landkreise, zukünftig Gemeinden

Angebotene Formate: Gesamt-CAP-files, ab 06.10.2015 als Test, ab 13.10.2015 operativ im Verzeichnis:
  - /gds/specials/alerts/cap/GER/…, (siehe in legend_warnings.xls, Register „Warnungen_CAP_Details“)

Angeboten wird der Gesamt-Warnstatus des DWD inkl. Binnensee-/Küsten-/Hitze- und künftig auch UV-Warnungen, mit und ohne Geometrie, sowie  ein Differenzfile CAP ohne Geometrie

Ein Beispiel für einen neuen Gesamt-CAP-Warntatus u.a. mit neuen WarnCell-IDs finden Sie schon jetzt unter gds/help:
legend_example_CAP_EDZW_20150922_065231_PVW_STATUS.zip
Eine fertige Visualisierung sollte identisch aussehen wie:
legend_example_CAP_EDZW_20150922_065231_PVW_STATUS_vis.png
Hinweis: Für das Berchtesgadener Land gibt es neben der visualisierten Unwetterwarnung in rot noch eine orange Warnung, die durch die höhere (rote) Warnung farblich „überdeckt“ wird. Bei Anzeige der Warnungen des Landkreises sollten alle nach Priorität erscheinen.

Unterschiede zu den Standard-Warnungen:
1. Auslieferung zeitlich hochaktuell
2. Gewitterwarnungen in  den gewohnten 16 Klassen (31-49 bzw. 94…96, siehe legend_warnings.xls, Register „Warnungen_Details“)

Anmerkung: wie beim Standard-Produkt entfällt auch hier zukünftig die Frostwarnung WW81, dafür wird die Frostwarnung WW22 ganzjährig ausgegeben (siehe legend_warnings.xls, Register „Warnungen_Details“)

!!!!! A C H T U N G !!!!!

Teilweise Änderung bei den WarnCell-IDs:
Systembedingt ändern sich in den CAP-files einige WarnCell-IDs, siehe Hervorhebungen in legend_warnings.xls, Register „Regionen“ Spalten M und N
D.h. für unten aufgeführten 32 (im DWD zusammen gefassten) Landkreisgebiete ändern sich die WarnCell-IDs nach folgendem Schema:

ALT:
10XXXX000

NEU:
90XXXX999

XXXX = variierende ID

Anschlussprozesse, die auf die bisherigen WarnCell-IDs aufsetzen müssen zwingend angepasst werden! Aufgrund eventuell möglicher Rückschaltungen auf das vorherige System empfehlen wir DRINGEND!!! eine zweigleisige Abfrage der WarnCell-IDs für die betroffenen Landkreisgebiete.

Weitere Produkte:
Die bislang unter /gds/specials/warnings/FG abgelegten Produkte werden unter /gds/specials/alerts/health abgelegt

Die bislang unter /gds/specials/warnings/maps abgelegten Grafiken werden unter /gds/specials/alerts/maps abgelegt

Die bislang unter /gds/specials/warnings/DL abgelegten Warnlageberichte werden unter /gds/specials/alerts/txt/GER abgelegt

Sollten sich o.g. Termine aus Gründen der Wetterlage oder unvorhergesehen technischen Problemen nochmals verschieben, werden wir Sie rechtzeitig informieren. Ggf. muss für eine Übergangszeit auf unsere Warnseite unter www.wettergefahren.de verwiesen werden.

Viele Grüße aus Offenbach
Ihr GDS-Team (gds.admin@dwd.de)

Liste der Landkreisgebiete, bei denen sich die WarnCell-IDs im Gesamt-CAP-File ändern:

DWD-Kennung   WarnCellId neu      WarnCellId alt   Warngebiet im DWD

OLX           903458999            103458000       Kreis und Stadt Oldenburg
OSX           903459999            103459000       Kreis und Stadt Osnabrück
AXX           909772999            109772000       Kreis und Stadt Augsburg
ABX           909671999            109671000       Kreis und Stadt Aschaffenburg
ANX           909571999            109571000       Kreis und Stadt Ansbach
BAX           909471999            109471000       Kreis und Stadt Bamberg
BTX           909472999            109472000       Kreis und Stadt Bayreuth
COX           909473999            109473000       Kreis und Stadt Coburg
FUE           909573999            109573000       Kreis und Stadt Fürth
HOX           909475999            109475000       Kreis und Stadt Hof
LAX           909274999            109274000       Kreis und Stadt Landshut
MXX           909184999            109184000       Kreis und Stadt München
PAX           909275999            109275000       Kreis und Stadt Passau
RXX           909375999            109375000       Kreis und Stadt Regensburg
ROX           909187999            109187000       Kreis und Stadt Rosenheim
SRX           909278999            109278000       Kreis Straubing-Bogen und Stadt Straubing
SWX           909678999            109678000       Kreis und Stadt Schweinfurt
WUE           909679999            109679000       Kreis und Stadt Würzburg
DAX           906432999            106432000       Kreis Darmstadt Dieburg und Stadt Darmstadt
KSX           906633999            106633000       Kreis und Stadt Kassel
OFX           906438999            106438000       Kreis und Stadt Offenbach
KLX           907335999            107335000       Kreis und Stadt Kaiserslautern
LUX           907338999            107338000       Rhein-Pfalz-Kreis und Stadt Ludwigshafen
MZX           907339999            107339000       Kreis Mainz-Bingen und Stadt Mainz
PSX           907340999            107340000       Kreis Südwestpfalz und Stadt Pirmasens
TRX           907235999            107235000       Kreis Trier-Saarburg und Stadt Trier
FRX           908315999            108315000       Kreis Breisgau Hochschwarzwald und Stadt Freiburg
HDX           908226999            108226000       Rhein-Neckar-Kreis und Stadt Heidelberg
HNX           908125999            108125000       Kreis und Stadt Heilbronn
KAX           908215999            108215000       Kreis und Stadt Karlsruhe
PFX           908236999            108236000       Enzkreis und Stadt Pforzheim
ULX           908425999            108425000       Alb-Donau-Kreis und Stadt Ulm

Ihr Warnungs- und GDS-Team

**Comment by GermanBluefox** [comment]
Danke.
Bitte testen

**Comment by grisuv** [comment]
Funktioniert soweit. 
Es wird jetzt wieder eine Datei abgerufen.
Jetzt nur noch auf eine Warnung warten.
Danke

**Comment by grisuv** [comment]
Irgendwie passt was immer noch nicht
MSP ist mein Landkreis

Im Pfad
/gds/specials/alerts/cap/MS/
gibt es im moment 3 MSP Dateien
zwei MSPX
und eine MSPC

alle MSPX werden geladen. beide sind aktuell schon abgelaufen
MSPC enthält die aktuelle warnung die auch auf DWD.de angezeigt wird.

leider aber nicht im dwd adapter

Ich weiß leider auch nicht was die MSPC (XXXC) für eine Bedeutung hat

**Comment by grisuv** [comment]
Ich habe es herausgefunden, nach langer suche
Es ist die Höhenstufe.
ftp://ftp-outgoing2.dwd.de/gds/help/legend_warnings.pdf
Evtl kann man ja noch irgendwie die Höhenstufe in die abfrage einbauen.

**Comment by GermanBluefox** [comment]
Kannst du jetzt probieren?
