### ISSUE TITLE
Whats new in 2.2.2 ?

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.dwd#11]
Can somebody please explain in detail what has been changed?

At least i don't have any idea what "changed sort order" means and if it will have any impact to my visualisation and other skripts.

Thanks

**Comment by Apollon77** [comment]
When I remember correctly it is about sorting for severity. So important events come first and unimportant last ... 
enough info?

**Comment by Apollon77** [comment]
More details here https://github.com/ioBroker/ioBroker.dwd/pull/10

**Comment by wendy2702** [comment]
Hi Apollon,

thanks for explanation and sorry for late reply. GitHub notification are sometimes sorted out as Spam by mail provider :-(
