### ISSUE TITLE
 has to be type "string" but received type "number"

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.dwd#120]
Seit längeren wird bei mir im LOG folgendes angezeigt:

![Unbenannt](https://user-images.githubusercontent.com/38273154/148235039-1fb93db3-dee2-4cf8-bee4-5bc468f5023c.PNG)

Bitte die States einmal fixen.

Danke

**Comment by Apollon77** [comment]
Bitte die betroffenen Objekte mal manuell löschen, Adater legt Sie neu an. Ist es dann weg?
