### ISSUE TITLE
New datapoint instruction

### ISSUE THREAD

**Issue by 1rfsNet** [ioBroker/ioBroker.dwd#121]
Currently I have the following JSON string in the "object" datapoint:
`{"regionName":"Berlin","state":"Berlin","type":1,"level":3,"description":"Es treten Sturmböen mit Geschwindigkeiten zwischen 60 km/h (17m/s, 33kn, Bft 7) und 70 km/h (20m/s, 38kn, Bft 8) anfangs aus westlicher, später aus nordwestlicher Richtung auf. In Schauernähe muss mit Sturmböen bis 75 km/h (21m/s, 41kn, Bft 9) gerechnet werden.","end":1642417200000,"start":1642395600000,"event":"STURMBÖEN","headline":"Amtliche WARNUNG vor STURMBÖEN","instruction":"ACHTUNG! Hinweis auf mögliche Gefahren: Es können zum Beispiel einzelne Äste herabstürzen. Achten Sie besonders auf herabfallende Gegenstände.","stateShort":"BL","altitudeStart":null,"altitudeEnd":null}`

Would it be possible to add another data point to the adapter containing the string in instruction?
The other data already has its own data points, but I have to extract the data from instruction from the JSON.

**Comment by Apollon77** [comment]
Please try GitHub version. addded there
