### ISSUE TITLE
Empty or invalid JSON: Cannot parse JSON file: SyntaxError: Unexpected token r in JSON at position 498496

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.dwd#126]
All tested JSON validators says the provided JSON from DWD is valid.
Is it a bug of adapter or is there really something wrong in the JSON?

[2022-02-06-dwd.zip](https://github.com/ioBroker/ioBroker.dwd/files/8010953/2022-02-06-dwd.zip)

adapter version: 2.7.7
JS-Controller: 3.3.22
nodejs: 14.19.0

**Comment by Apollon77** [comment]
If it happens again then check for /opt/iobroker/node_modules/iobroker.dwd/lib/problem.json ... this contains the downloaded json

**Comment by Diginix** [comment]
Today it happend ahain and yes, the saved JSON is invalid. Presumably it is not solvable within the adapter.
https://www.dropbox.com/s/mkvzw1pihvl1qio/2022-05-19_1900_dwd_problem.json?dl=0

**Comment by Apollon77** [comment]
exactly :-(
