### ISSUE TITLE
Inconsistency with objects from Adapter

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.dwd#13]
Can you please check the following issue at iobroker Forum?

https://forum.iobroker.net/viewtopic.php?f=20&t=14384

If needed i can upload and explain problem here as well. Please let me know.

**Comment by GermanBluefox** [comment]
I Cannon see any inconsistencies there.

**Comment by wendy2702** [comment]
Can you please help as i still got invalid data. Any hint how to troubleshoot?

**Comment by GermanBluefox** [comment]
I guess, I can close the issue? 
https://forum.iobroker.net/viewtopic.php?f=20&t=14384&sid=2574f6cd6b2896ab33c6141b85e07a21&start=20#p165433

**Comment by wendy2702** [comment]
Seems  to be a problem at DWD !
