### ISSUE TITLE
Warning0 new without object in object-DP 

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.dwd#137]
Vorher gab es kein warning0-DP. Jetzt wird ein er erzeugt, dem fehlen aber die object-Strukturen. {} in object.
![image](https://user-images.githubusercontent.com/84818934/159703988-4c88cd62-ba96-4702-a39f-835431cbe8e5.png)
warning1 sieht so aus:
![image](https://user-images.githubusercontent.com/84818934/159704079-8912b269-54c7-4ae1-8884-4d0569a7313d.png)
warning0 macht auch keinen Sinn da es schon warning gibt? Oder man muss den Inhalt von warning auf warning0 setzen?

![image](https://user-images.githubusercontent.com/84818934/159710239-61433e3f-11e6-4206-b91c-0aa70726540e.png)

Nach einiger Zeit ist plötzlich die waning0 weg? Kontrolliert der Adapter nach einiger Zeit die DPs?
![image](https://user-images.githubusercontent.com/84818934/159713684-71a00b38-7a8f-465e-a341-f3327f1077e9.png)
Jetzt wieder da?
![image](https://user-images.githubusercontent.com/84818934/159727483-1268265d-d970-48d7-9cf3-33fb436f9bdb.png)

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by mcuiobroker** [comment]
Ja. Passt. Danke.
