### ISSUE TITLE
some regions don't work

### ISSUE THREAD

**Issue by TomT1965** [ioBroker/ioBroker.dwd#14]
seems that DWD has changed regions and so i can't get any warnings.

Here it is "Altenkirchen (Westerwald)" which has been titled "Kreis Altenkirchen" before.

Any suggestions what to do?
 please also see : https://forum.iobroker.net/viewtopic.php?f=20&t=14505

Greetings Tom

**Comment by GermanBluefox** [comment]
Da wurde viel geändert. Ich habe noch keine Zeit die neue Logik zu verstehen.
Würde dankbar sein, wenn jemand schauen konnte.

**Comment by GermanBluefox** [comment]
https://www.dwd.de/DWD/warnungen/warnapp_gemeinden/viewer/gemeinden.js?v=2

**Comment by GermanBluefox** [comment]
Hat vielleicht das damit zu tun?
https://www.dwd.de/DE/leistungen/warnungen/aenderungen_cap.html?nn=508722

**Comment by GermanBluefox** [comment]
Test 2.4.0

**Comment by DeepCoreSystem** [comment]
Die Gemeinden/Städte vom Update 2.4.0 werden mit dem "Standard"-JSON [https://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json](url) vom DWD nicht funktionieren, weil im JSON nur Daten für Landkreise geliefert werden,

Die Daten auf Gemeindeebene werden nur über den DWD-GeoWebService als WebFeatureService(WFS) angeboten. [https://www.dwd.de/DE/leistungen/geowebservice/geowebservice.html?nn=508722](url)

**Comment by GermanBluefox** [comment]
Kann ich das schließen?

**Comment by notkom** [comment]
> Die Gemeinden/Städte vom Update 2.4.0 werden mit dem "Standard"-JSON [https://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json](url) vom DWD nicht funktionieren, weil im JSON nur Daten für Landkreise geliefert werden,
> 
> Die Daten auf Gemeindeebene werden nur über den DWD-GeoWebService als WebFeatureService(WFS) angeboten. [https://www.dwd.de/DE/leistungen/geowebservice/geowebservice.html?nn=508722](url)

Bedeutet das, dass das Integrieren von Gemeinden und Städten technisch nicht möglich ist?

**Comment by Apollon77** [comment]
Hm ... an sich sollte es ja gehen, man muss "nur" einen wfs client nutzen und es halt einbauen ... Falls die Daten "frei Verfügbar" sind

**Comment by DeepCoreSystem** [comment]
Hier mal ein Abfrage-Beispiel um die Liste der Gemeinden mit derer ID zu erhalten. Die Daten werden bei der Abfrage gefiltert und dann im JSON Format heruntergeladen. Das Filtern und Format ist sehr wichtig, denn ohne Filter kommen gut 15 MB im XML Format durch die Leitung.

https://maps.dwd.de/geoserver/ows?service=wfs&version=2.0.0&request=GetFeature&TYPENAMES=dwd:Warngebiete_Gemeinden&OUTPUTFORMAT=json&propertyname=WARNCELLID,NAME

Wenn mann dann seine WARNCELLID hat, können entsprechend gefilterte Anfragen gemacht werden:

https://maps.dwd.de/geoserver/ows?service=wfs&version=2.0.0&request=GetFeature&TYPENAMES=dwd:Warnungen_Gemeinden&OUTPUTFORMAT=json&CQL_FILTER=WARNCELLID=....
