### ISSUE TITLE
Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

### ISSUE THREAD

**Issue by JNDMNK** [ioBroker/ioBroker.dwd#153]
2022-11-04 07:10:05.145 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

2022-11-04 07:10:02.863 | info | starting. Version 2.8.3 in /opt/iobroker/node_modules/iobroker.dwd, node: v16.18.0, js-controller: 4.0.23

Screenshots

![Log](https://user-images.githubusercontent.com/73331497/199904242-5d0f4676-6fcf-4520-87af-00c99d8f8c33.jpg)

**Versions:**  
 - Adapter version: v2.8.3
 - JS-Controller version: 16.18.0
 - Node version: 8.19.2
 - Operating system: linux

**Comment by Apollon77** [comment]
Ok, ja und was ist jetzt das Problem? Dieses Logging ist normal bei einem Adapter der in eine definierten Schedule gestartet wird, seine Arbeit tut und sich beendet

**Comment by JNDMNK** [comment]
So oft hintereinander in kurzer Zeit?

**Comment by Apollon77** [comment]
Ja was ist denn als schedule eingestellt? Sieht nach "alle 5 Minuten" aus ... das wäre der Standard Schedule

**Comment by JNDMNK** [comment]
ah ok dann sorry, mein fehler. Bin davon ausgeagngen da Ohne Grund da steht das es nicht normal ist.
