### ISSUE TITLE
Updated cities don't match the JSON data from DWD

### ISSUE THREAD

**Issue by DeepCoreSystem** [ioBroker/ioBroker.dwd#17]
The standard JSONP file available under [https://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json](url) doesn't provide information at the cities level, only district level.

The cities level information is only available through the DWD GeoWebService as WebFeatureService(WFS).

More information about available data can be found here [https://www.dwd.de/DE/wetter/warnungen_aktuell/objekt_einbindung/objekteinbindung.html](url)

**Comment by GermanBluefox** [comment]
I read this page yesterday 5 times. But I cant find the list of possible cities. :(

**Comment by GermanBluefox** [comment]
I updated now the list of cities

**Comment by DeepCoreSystem** [comment]
Hi Bluefox,

here is the actual district and cities list from DWD.




WARNCELLID	NAME
101001000	Stadt Flensburg
101002000	Stadt Kiel
101003000	Hansestadt Lbeck
101004000	Stadt Neumnster
101053000	Kreis Herzogtum Lauenburg
101060000	Kreis Segeberg
101061000	Kreis Steinburg
101062000	Kreis Stormarn
102000000	Hansestadt Hamburg
103101000	Stadt Braunschweig
103102000	Stadt Salzgitter
103103000	Stadt Wolfsburg
103151000	Kreis Gifhorn
103153000	Kreis Goslar
103154000	Kreis Helmstedt
103155000	Kreis Northeim
103157000	Kreis Peine
103158000	Kreis Wolfenbttel
103159000	Kreis G”ttingen
103241000	Region Hannover
103251000	Kreis Diepholz
103252000	Kreis Hameln-Pyrmont
103254000	Kreis Hildesheim
103255000	Kreis Holzminden
103256000	Kreis Nienburg
103257000	Kreis Schaumburg
103351000	Kreis Celle
103353000	Kreis Harburg
103354000	Kreis Lchow-Dannenberg
103355000	Kreis Lneburg
103356000	Kreis Osterholz
103357000	Kreis Rotenburg (Wmme)
103358000	Heidekreis
103359000	Kreis Stade
103360000	Kreis Uelzen
103361000	Kreis Verden
103401000	Stadt Delmenhorst
103402000	Stadt Emden
103405000	Stadt Wilhelmshaven
103451000	Kreis Ammerland
103453000	Kreis Cloppenburg
103454000	Kreis Emsland
103456000	Kreis Grafschaft Bentheim
103460000	Kreis Vechta
104011000	Hansestadt Bremen
104012000	Stadt Bremerhaven
105111000	Stadt Dsseldorf
105112000	Stadt Duisburg
105113000	Stadt Essen
105114000	Stadt Krefeld
105116000	Stadt M”nchengladbach
105117000	Stadt Mlheim an der Ruhr
105119000	Stadt Oberhausen
105120000	Stadt Remscheid
105122000	Stadt Solingen
105124000	Stadt Wuppertal
105154000	Kreis Kleve
105158000	Kreis Mettmann
105162000	Rhein-Kreis Neuss
105166000	Kreis Viersen
105170000	Kreis Wesel
105314000	Bundesstadt Bonn
105315000	Stadt K”ln
105316000	Stadt Leverkusen
105334000	St„dteRegion Aachen
105358000	Kreis Dren
105362000	Rhein-Erft-Kreis
105366000	Kreis Euskirchen
105370000	Kreis Heinsberg
105374000	Oberbergischer Kreis
105378000	Rheinisch-Bergischer Kreis
105382000	Rhein-Sieg-Kreis
105512000	Stadt Bottrop
105513000	Stadt Gelsenkirchen
105515000	Stadt Mnster
105554000	Kreis Borken
105558000	Kreis Coesfeld
105562000	Kreis Recklinghausen
105566000	Kreis Steinfurt
105570000	Kreis Warendorf
105711000	Stadt Bielefeld
105754000	Kreis Gtersloh
105758000	Kreis Herford
105762000	Kreis H”xter
105766000	Kreis Lippe
105770000	Kreis Minden-Lbbecke
105774000	Kreis Paderborn
105911000	Stadt Bochum
105913000	Stadt Dortmund
105914000	Stadt Hagen
105915000	Stadt Hamm
105916000	Stadt Herne
105954000	Ennepe-Ruhr-Kreis
105958000	Hochsauerlandkreis
105962000	M„rkischer Kreis
105966000	Kreis Olpe
105970000	Kreis Siegen-Wittgenstein
105974000	Kreis Soest
105978000	Kreis Unna
106412000	Stadt Frankfurt am Main
106414000	Stadt Wiesbaden
106431000	Kreis Bergstraáe
106433000	Kreis Groá-Gerau
106434000	Hochtaunuskreis
106435000	Main-Kinzig-Kreis und Stadt Hanau
106436000	Main-Taunus-Kreis
106437000	Odenwaldkreis
106439000	Rheingau-Taunus-Kreis
106440000	Wetteraukreis
106531000	Kreis Gieáen
106532000	Lahn-Dill-Kreis
106533000	Kreis Limburg-Weilburg
106534000	Kreis Marburg-Biedenkopf
106535000	Vogelsbergkreis
106631000	Kreis Fulda
106632000	Kreis Hersfeld-Rotenburg
106634000	Schwalm-Eder-Kreis
106635000	Kreis Waldeck-Frankenberg
106636000	Werra-Meissner-Kreis
107111000	Stadt Koblenz
107131000	Kreis Ahrweiler
107132000	Kreis Altenkirchen
107133000	Kreis Bad Kreuznach
107134000	Kreis Birkenfeld
107135000	Kreis Cochem-Zell
107137000	Kreis Mayen-Koblenz
107138000	Kreis Neuwied
107140000	Rhein-Hunsrck-Kreis
107141000	Rhein-Lahn-Kreis
107143000	Westerwaldkreis
107231000	Kreis Bernkastel-Wittlich
107232000	Eifelkreis Bitburg-Prm
107233000	Kreis Vulkaneifel
107311000	Stadt Frankenthal
107313000	Stadt Landau in der Pfalz
107316000	Stadt Neustadt an der Weinstraáe
107318000	Stadt Speyer
107319000	Stadt Worms
107320000	Stadt Zweibrcken
107331000	Kreis Alzey-Worms
107332000	Kreis Bad Drkheim
107333000	Donnersbergkreis
107334000	Kreis Germersheim
107336000	Kreis Kusel
107337000	Kreis Sdliche Weinstraáe
108111000	Stadt Stuttgart
108115000	Kreis B”blingen
108116000	Kreis Esslingen
108117000	Kreis G”ppingen
108118000	Kreis Ludwigsburg
108119000	Rems-Murr-Kreis
108126000	Hohenlohekreis
108127000	Kreis Schw„bisch Hall
108128000	Main-Tauber-Kreis
108135000	Kreis Heidenheim
108136000	Ostalbkreis
108211000	Stadt Baden-Baden
108216000	Kreis Rastatt
108222000	Stadt Mannheim
108225000	Neckar-Odenwald-Kreis
108235000	Kreis Calw
108237000	Kreis Freudenstadt
108316000	Kreis Emmendingen
108317000	Ortenaukreis
108325000	Kreis Rottweil
108326000	Schwarzwald-Baar-Kreis
108327000	Kreis Tuttlingen
108335000	Kreis Konstanz
108336000	Kreis L”rrach
108337000	Kreis Waldshut
108415000	Kreis Reutlingen
108416000	Kreis Tbingen
108417000	Zollernalbkreis
108426000	Kreis Biberach
108435000	Bodenseekreis
108436000	Kreis Ravensburg
108437000	Kreis Sigmaringen
109161000	Stadt Ingolstadt
109171000	Kreis Alt”tting
109172000	Kreis Berchtesgadener Land
109173000	Kreis Bad T”lz-Wolfratshausen
109174000	Kreis Dachau
109175000	Kreis Ebersberg
109176000	Kreis Eichst„tt
109177000	Kreis Erding
109178000	Kreis Freising
109179000	Kreis Frstenfeldbruck
109180000	Kreis Garmisch-Partenkirchen
109181000	Kreis Landsberg am Lech
109182000	Kreis Miesbach
109183000	Kreis Mhldorf a. Inn
109185000	Kreis Neuburg-Schrobenhausen
109186000	Kreis Pfaffenhofen a.d. Ilm
109188000	Kreis Starnberg
109189000	Kreis Traunstein
109190000	Kreis Weilheim-Schongau
109271000	Kreis Deggendorf
109272000	Kreis Freyung-Grafenau
109273000	Kreis Kelheim
109276000	Kreis Regen
109277000	Kreis Rottal-Inn
109279000	Kreis Dingolfing-Landau
109361000	Stadt Amberg
109363000	Stadt Weiden in der Oberpfalz
109371000	Kreis Amberg-Sulzbach
109372000	Kreis Cham
109373000	Kreis Neumarkt i.d. OPf.
109374000	Kreis Neustadt a.d. Waldnaab
109376000	Kreis Schwandorf
109377000	Kreis Tirschenreuth
109474000	Kreis Forchheim
109476000	Kreis Kronach
109477000	Kreis Kulmbach
109478000	Kreis Lichtenfels
109479000	Kreis Wunsiedel
109562000	Stadt Erlangen
109564000	Stadt Nrnberg
109565000	Stadt Schwabach
109572000	Kreis Erlangen-H”chstadt
109574000	Kreis Nrnberger Land
109575000	Kreis Neustadt a.d. Aisch - Bad Windsheim
109576000	Kreis Roth
109577000	Kreis Weiáenburg-Gunzenhausen
109672000	Kreis Bad Kissingen
109673000	Kreis Rh”n-Grabfeld
109674000	Kreis Haáberge
109675000	Kreis Kitzingen
109676000	Kreis Miltenberg
109677000	Kreis Main-Spessart
109762000	Stadt Kaufbeuren
109763000	Stadt Kempten (Allg„u)
109764000	Stadt Memmingen
109771000	Kreis Aichach-Friedberg
109773000	Kreis Dillingen a.d. Donau
109774000	Kreis Gnzburg
109775000	Kreis Neu-Ulm
109776000	Kreis Lindau
109777000	Kreis Ostallg„u
109778000	Kreis Unterallg„u
109779000	Kreis Donau-Ries
109780000	Kreis Oberallg„u
110041000	Regionalverband Saarbrcken
110042000	Kreis Merzig-Wadern
110043000	Kreis Neunkirchen
110044000	Kreis Saarlouis
110045000	Saarpfalz-Kreis
110046000	Kreis St. Wendel
111000000	Berlin
112051000	Stadt Brandenburg
112052000	Stadt Cottbus
112053000	Stadt Frankfurt (Oder)
112054000	Stadt Potsdam
112060000	Kreis Barnim
112061000	Kreis Dahme-Spreewald
112062000	Kreis Elbe-Elster
112063000	Kreis Havelland
112064000	Kreis M„rkisch-Oderland
112065000	Kreis Oberhavel
112066000	Kreis Oberspreewald-Lausitz
112067000	Kreis Oder-Spree
112068000	Kreis Ostprignitz-Ruppin
112069000	Kreis Potsdam-Mittelmark
112070000	Kreis Prignitz
112071000	Kreis Spree-Neiáe
112072000	Kreis Teltow-Fl„ming
112073000	Kreis Uckermark
113003000	Hansestadt Rostock
113004000	Stadt Schwerin
114511000	Stadt Chemnitz
114521000	Erzgebirgskreis
114612000	Stadt Dresden
114627000	Kreis Meiáen
114713000	Stadt Leipzig
114729000	Kreis Leipzig
115001000	Stadt Dessau-Roálau
115002000	Stadt Halle (Saale)
115003000	Stadt Magdeburg
115081000	Altmarkkreis Salzwedel
115082000	Kreis Anhalt-Bitterfeld
115083000	Kreis B”rde
115084000	Burgenlandkreis
115086000	Kreis Jerichower Land
115087000	Kreis Mansfeld-Sdharz
115088000	Saalekreis
115089000	Salzlandkreis
115090000	Kreis Stendal
115091000	Kreis Wittenberg
116051000	Stadt Erfurt
116052000	Stadt Gera
116053000	Stadt Jena
116054000	Stadt Suhl
116055000	Stadt Weimar
116056000	Stadt Eisenach
116061000	Kreis Eichsfeld
116062000	Kreis Nordhausen
116063000	Wartburgkreis
116064000	Unstrut-Hainich-Kreis
116065000	Kyffh„userkreis
116066000	Kreis Schmalkalden-Meiningen
116067000	Kreis Gotha
116068000	Kreis S”mmerda
116069000	Kreis Hildburghausen
116070000	Ilm-Kreis
116071000	Kreis Weimarer Land
116072000	Kreis Sonneberg
116073000	Kreis Saalfeld-Rudolstadt
116074000	Saale-Holzland-Kreis
116075000	Saale-Orla-Kreis
116076000	Kreis Greiz
116077000	Kreis Altenburger Land
901051001	Kreis Dithmarschen - Binnenland
901051002	Kreis Dithmarschen - Kste
901054001	Kreis Nordfriesland - Binnenland
901054002	Kreis Nordfriesland - Kste
901055001	Kreis Ostholstein - Binnenland
901055002	Kreis Ostholstein - Kste
901056001	Kreis Pinneberg
901056002	Insel Helgoland
901057001	Kreis Pl”n - Binnenland
901057002	Kreis Pl”n - Kste
901058001	Kreis Rendsburg-Eckernf”rde - Binnenland
901058002	Kreis Rendsburg-Eckernf”rde - Kste
901059001	Kreis Schleswig-Flensburg - Binnenland
901059002	Kreis Schleswig-Flensburg - Kste
903352001	Kreis Cuxhaven - Binnenland
903352002	Kreis Cuxhaven - Kste
903452001	Kreis Aurich - Binnenland
903452002	Kreis Aurich - Kste
903455001	Kreis Friesland - Binnenland
903455002	Kreis Friesland - Kste
903457001	Kreis Leer
903457002	Insel Borkum
903458999	Kreis und Stadt Oldenburg
903459999	Kreis und Stadt Osnabrck
903461001	Kreis Wesermarsch - Binnenland
903461002	Kreis Wesermarsch - Kste
903462001	Kreis Wittmund - Binnenland
903462002	Kreis Wittmund - Kste
906432999	Kreis Darmstadt-Dieburg und Stadt Darmstadt
906438999	Kreis und Stadt Offenbach
906633999	Kreis und Stadt Kassel
907235999	Kreis Trier-Saarburg und Stadt Trier
907335999	Kreis und Stadt Kaiserslautern
907338999	Rhein-Pfalz-Kreis und Stadt Ludwigshafen
907339999	Kreis Mainz-Bingen und Stadt Mainz
907340999	Kreis Sdwestpfalz und Stadt Pirmasens
908125999	Kreis und Stadt Heilbronn
908215999	Kreis und Stadt Karlsruhe
908226999	Rhein-Neckar-Kreis und Stadt Heidelberg
908236999	Enzkreis und Stadt Pforzheim
908315999	Kreis Breisgau-Hochschwarzwald und Stadt Freiburg
908425999	Alb-Donau-Kreis und Stadt Ulm
909184999	Kreis und Stadt Mnchen
909187999	Kreis und Stadt Rosenheim
909274999	Kreis und Stadt Landshut
909275999	Kreis und Stadt Passau
909278999	Kreis Straubing-Bogen und Stadt Straubing
909375999	Kreis und Stadt Regensburg
909471999	Kreis und Stadt Bamberg
909472999	Kreis und Stadt Bayreuth
909473999	Kreis und Stadt Coburg
909475999	Kreis und Stadt Hof
909571999	Kreis und Stadt Ansbach
909573999	Kreis und Stadt Frth
909671999	Kreis und Stadt Aschaffenburg
909678999	Kreis und Stadt Schweinfurt
909679999	Kreis und Stadt Wrzburg
909772999	Kreis und Stadt Augsburg
913071001	Kreis Mecklenburgische Seenplatte - Nord
913071002	Kreis Mecklenburgische Seenplatte - West
913071003	Kreis Mecklenburgische Seenplatte - Sdost
913072001	Kreis Rostock - Binnenland Nord
913072002	Kreis Rostock - Kste
913072003	Kreis Rostock - Binnenland Sd
913073001	Kreis Vorpommern-Rgen - Binnenland
913073002	Kreis Vorpommern-Rgen - Kste
913073003	Kreis Vorpommern-Rgen - Insel Rgen
913074001	Kreis Nordwestmecklenburg - Binnenland
913074002	Kreis Nordwestmecklenburg - Kste
913075001	Kreis Vorpommern-Greifswald - Binnenland Nord
913075002	Kreis Vorpommern-Greifswald - Kste Nord
913075003	Kreis Vorpommern-Greifswald - Binnenland Sd
913075004	Kreis Vorpommern-Greifswald - Kste Sd
913076001	Kreis Ludwigslust-Parchim - West
913076002	Kreis Ludwigslust-Parchim - Ost
914522001	Kreis Mittelsachsen - Tiefland
914522002	Kreis Mittelsachsen - Bergland
914523001	Vogtlandkreis - Tiefland
914523002	Vogtlandkreis - Bergland
914524001	Kreis Zwickau - Tiefland
914524002	Kreis Zwickau - Bergland
914625001	Kreis Bautzen - Tiefland
914625002	Kreis Bautzen - Bergland
914626001	Kreis G”rlitz - Tiefland
914626002	Kreis G”rlitz - Bergland
914628001	Kreis S„chsische Schweiz-Osterzgebirge - Tiefland
914628002	Kreis S„chsische Schweiz-Osterzgebirge - westelbisches Bergland
914628003	Kreis S„chsische Schweiz-Osterzgebirge - ostelbisches Bergland
914730001	Kreis Nordsachsen - Nord
914730002	Kreis Nordsachsen - Sd
915085001	Kreis Harz - Tiefland
915085002	Kreis Harz - Bergland

**Comment by GermanBluefox** [comment]
Where have you got the list? Because some Umlauts are broken.

ср, 1 авг. 2018 г., 17:26 DeepCoreSystem <notifications@github.com>:

**Comment by DeepCoreSystem** [comment]
Hi Bluefox,

I fetch the lists from the follwing links. You can change the output 
format to CSV by using OUTPUTFORMAT=csv. If you omit OUTPUTFORMAT, 
you'll receive it in XML.

I miss the "good, old days" where we only had ASCII coding ... ;o)

There are some more warning regions available: Warngebiete_See / 
Warngebiete_Binnenseen / Warngebiete_Kueste / Warngebiete_Bundeslaender

But I don't know if they are used in the JSON warning file... Through 
the geoserver they are available...


District list:
https://maps.dwd.de/geoserver/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&TYPENAMES=Warngebiete_Kreise&OUTPUTFORMAT=json

Cities list:
https://maps.dwd.de/geoserver/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&TYPENAMES=Warngebiete_Gemeinden&OUTPUTFORMAT=json

**Comment by GermanBluefox** [comment]
The list was updated from https://maps.dwd.de/geoserver/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&TYPENAMES=Warngebiete_Kreise&OUTPUTFORMAT=json
