### ISSUE TITLE
Empty or invalid JSON: Cannot read JSON file: Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by Harald-B-Rupp** [ioBroker/ioBroker.dwd#19]
Since yesterday night 30.08.2018, the DWD Adapter reports an Error, which causes that no Weather Warning Data could be anymore retrieved by IoBroker 

The Error Message contains: 

Empty or invalid JSON: Cannot read JSON file: Error: unable to verify the first certificate
--
I could reproduce this using Adapter Version 2.2.2 and 2.4.2.

**Comment by ceotjoe** [comment]
same here

**Comment by lordnaicon** [comment]
Hi bei mir das selbe:

> 

dwd.0 | 2018-09-01 22:50:02.729 | error | Empty or invalid JSON: Cannot read JSON file: Error: unable to verify the first certificate
-- | -- | -- | --
dwd.0 | 2018-09-01 22:50:02.323 | info | starting. Version 2.4.2 in /root/node_modules/iobroker.dwd, node: v6.14.1

Mfg

**Comment by heckmic** [comment]
Habe aktuelle auch genau das Problem: Empty or invalid JSON: Cannot read JSON file: AxiosError: Request failed with status code 503

**Comment by Apollon77** [comment]
503 ist ein temporärer Fehler auf Server Seite. EInfach abwarten - sollte sich wieder fixen von allein
