### ISSUE TITLE
DWD-Adapter: fehlende Anzeige von Glätte, Nebel,..

### ISSUE THREAD

**Issue by PrinzEisenherz1** [ioBroker/ioBroker.dwd#2]
Derzeit werden bundesweit keine Warnmeldung des Typs Glätte, Nebel und eventuell noch anderer (konnte nur anhand bestehender Warnmeldungen durch DWD testen) nicht angezeigt!
Zur zeit zeigt der Adapter Warnmeldungen des Typs .....BÖEN und ....SCHNEE an.

Gruß
Johnny

**Comment by GermanBluefox** [comment]
Sollte besser sein mit der neuen Version.

**Comment by PrinzEisenherz1** [comment]
Hi Bluefox!
Hat leider nicht geklappt! Bekomme immer ne error Meldung im log!
"
host-raspberrypi   2016-03-16 18:35:30   error   instance
system.adapter.dwd.0 terminated with code 8 (node.js: Cannot find module)"
Das Problem ist erst seit der Version 2.0.1

Gruß Johnny
Am 16.03.2016 18:03 schrieb "GermanBluefox" <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Ist doch schon längst erledigt, oder?

**Comment by PrinzEisenherz1** [comment]
Ich glaub da hast du dich wohl jetzt mit dem jahr vertan. Das war vor nem Jahr und ist schon lange erledigt

**Comment by Apollon77** [comment]
Na dann zu damit :-)
