### ISSUE TITLE
Array maps stimmt nicht mit typ-Information überein

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.dwd#20]
Hallo,

das Array maps stimmt leiden mit der type-Information nicht überein, weshalb die png's nicht die richtigen zur Meldung sind.

Gruß
Thomas Hirschfeld

**Comment by GermanBluefox** [comment]
Immer noch offen?

**Comment by Hirsch-DE** [comment]
ist erledigt.






Re: [ioBroker/ioBroker.dwd] Array maps stimmt nicht mit typ-Information überein (#20) 24. Februar 2020, 18:32 Uhr 
Von Bluefox 
An ioBroker/ioBroker.dwd 
Cc (2) Thomas Hirschfeld|Author 


Immer noch offen?
