### ISSUE TITLE
Begin and end date of the warnings

### ISSUE THREAD

**Issue by sammie76-2** [ioBroker/ioBroker.dwd#216]
The begin and the end date are in english at the moment in the dwd adapter. Is there a way to convert this information to german? 

When not possible to do this in the adapter is there another way to convert this in iobroker? 

Thanks for a feedback to this.

**Comment by Apollon77** [comment]
What does "Date is in english" means? Please provide screenshots and such and also potentially a debug log

**Comment by sammie76-2** [comment]
Problem already solved. Sorry for that! Could be closed.
