### ISSUE TITLE
Empty or invalid JSON

### ISSUE THREAD

**Issue by PrinzEisenherz1** [ioBroker/ioBroker.dwd#22]
Ich verwende Version 2.4.3 und da erscheint des öfteren folgende Fehlermeldung

`dwd.0	2018-10-15 07:45:01.887	error	Empty or invalid JSON: Cannot read JSON file: null`

Gruß
Johnny

**Comment by Diginix** [comment]
Auch mit Ver 2.5.1 erhalte ich immer wieder mal über Stunden verteilt:
"Empty or invalid JSON: Cannot read JSON file: null"

**Comment by Apollon77** [comment]
Naja das heisst das der Webserver nichts liefert

**Comment by Diginix** [comment]
Mag sein. Wenn es aber ein normales oder eben zu erwartendes Verhalten vom DWD ist, dann ist es als error Eintrag im Log und das wiederholend bis mal wieder ein gefülltes JSON kommt, unschön. Ein leeres JSON ist ja kein Fehler, viel mehr ist der Fehler, dass es als Fehler gemeldet wird. ;-)
Vllt könnte man das unterdrücken oder auf Level info setzen bzw. in der Instanz konfigurierbar machen.
Ich versuche mein Log maximal klein zu halten und habe div. Adapter bereits auf Level warn, damit mir info Zeilen nicht die Übersicht nehmen. Wäre es nur info, würde es bei mir unter dem Radar bleiben.

**Comment by Apollon77** [comment]
Ich würde ja an sich annehmen das das eher NICHT passiert, wenn es also mehrfach passiert ist das blöd. Also ja kann man gern als Info loggen, andererseits kommen dann (und das verspreche ich fast schon weil ich drauf warten kann) bald andere User mit "der Adapter geht nicht" weil Sie nämlich das Log nicht sehen. Was ist also jetzt richtig?
