### ISSUE TITLE
Receive no actual warning for my region

### ISSUE THREAD

**Issue by Wello72** [ioBroker/ioBroker.dwd#23]
Hi,

at the moment there is a warning from DWD for my Region.

This region is also set in the DWD Adapter config:

Kreis Neustadt a.d. Aisch - Bad Windsheim

After saving the configs, the following lines are visible in the log:

 `dwd.0 | 2018-12-03 13:15:03.333 | debug | Add warning "dwd.0.warning2":
dwd.0 | 2018-12-03 13:15:03.333 | debug | Add warning "dwd.0.warning1":
dwd.0 | 2018-12-03 13:15:03.332 | debug | Add warning "dwd.0.warning":
dwd.0 | 2018-12-03 13:15:01.833 | info | starting. Version 2.4.3 in /opt/iobroker/node_modules/iobroker.dwd, node: v8.14.0

`
In the objects also nothing is displayed, empty warnings and so on.

Changing to a the neighbour region (Kreis und Stadt Ansbach) displays the actual warnings for this region, e.g.

`
Warning begin | state | date.start |   |   | Mon Mar 12 2018 13:17:00 GMT+0100 (Mitteleuropäische Normalzeit) |
description | Warning description | state | weather.state |   |   | Von Westen ziehen Gewitter auf. Dabei gibt es Sturmböen mit Geschwindigkeiten bis 70 km/h (20m/s, 38kn, Bft 8) sowie Starkregen mit Niederschlagsmengen bis 20 l/m² in kurzer Zeit. | 
end | Warning end | state | date.end |   |   | Mon Mar 12 2018 15:00:00 GMT+0100 (Mitteleuropäische Normalzeit) | 
headline | Warning headline | state | weather.title |   |   | Amtliche WARNUNG vor STARKEM GEWITTER | 
level | Warning level | state | value.warning |   |   | Moderate(3)

`

Installed is version 2.4.3 at the moment. Uninstalling, reinstall didn't help, always the same behaviour when choosing my region.

**Comment by Wello72** [comment]
Same today, attached now some screenshots from my config, the DWD website and so on. 
![2018-12-07 12_57_00-window](https://user-images.githubusercontent.com/26403464/49646620-ddfbd880-fa1f-11e8-8035-80c30f193992.jpg)

![2018-12-07 12_57_32-window](https://user-images.githubusercontent.com/26403464/49646628-e48a5000-fa1f-11e8-9632-e2ca51639991.jpg)

![2018-12-07 12_58_09-window](https://user-images.githubusercontent.com/26403464/49646637-ea803100-fa1f-11e8-96de-c8ad2f8d9655.jpg)

and still nothing special in the log:

![2018-12-07 13_02_29-window](https://user-images.githubusercontent.com/26403464/49646763-6bd7c380-fa20-11e8-83f6-69183245420d.jpg)

**Comment by GermanBluefox** [comment]
Please always check https://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json
If your region is inside.
