### ISSUE TITLE
Download only one warning

### ISSUE THREAD

**Issue by Isolevel** [ioBroker/ioBroker.dwd#24]
Hi @ all,
I’ve configured the adapter to download three warnings, I’ve selected a region where we have currently more than one warning (Kreis Garmisch-Partenkirchen -> four active warnings, see extract below from https://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json) and I’ve got only one warning to my objects.

I'm not sure if I should check your code...

![image](https://user-images.githubusercontent.com/46327047/50605386-77ed5e80-0ec2-11e9-8fdc-5c4de29fb450.png)

![image](https://user-images.githubusercontent.com/46327047/50605418-89366b00-0ec2-11e9-8cf9-103f3b1def66.png)

"109180000":[{"regionName":"Kreis Garmisch-Partenkirchen","start":1546372800000,"end":1546459200000,"type":3,"state":"Bayern","level":3,"stateShort":"BY","description":"Es tritt im Warnzeitraum Schneefall mit Mengen zwischen 10 cm und 20 cm auf. In Staulagen werden Mengen bis 30 cm erreicht. Die Schneefallgrenze fällt bis in tiefe Lagen. Verbreitet wird es glatt.","altitudeStart":null,"altitudeEnd":null,"headline":"Amtliche WARNUNG vor SCHNEEFALL","instruction":"","event":"SCHNEEFALL"},
{"regionName":"Kreis Garmisch-Partenkirchen","start":1546351200000,"end":1546470000000,"type":1,"state":"Bayern","level":3,"stateShort":"BY","description":"Es treten oberhalb 1500 m Sturmböen mit Geschwindigkeiten um 80km/h (22m/s, 44kn, Bft 9) anfangs aus westlicher, später aus nordwestlicher Richtung auf. In exponierten Lagen muss mit schweren Sturmböen um 90 km/h (25m/s, 48kn, Bft 10) gerechnet werden.","altitudeStart":1500,"altitudeEnd":null,"headline":"Amtliche WARNUNG vor STURMBÖEN","instruction":"ACHTUNG! Hinweis auf mögliche Gefahren: Es können zum Beispiel einzelne Äste herabstürzen. Achten Sie besonders auf herabfallende Gegenstände.","event":"STURMBÖEN"},
{"regionName":"Kreis Garmisch-Partenkirchen","start":1546448400000,"end":1546506000000,"type":6,"state":"Bayern","level":2,"stateShort":"BY","description":"Es muss mit Glätte durch verbreitet überfrierende Nässe sowie geringfügigen Schneefall gerechnet werden.","altitudeStart":null,"altitudeEnd":null,"headline":"Amtliche WARNUNG vor GLÄTTE","instruction":"","event":"GLÄTTE"},
{"regionName":"Kreis Garmisch-Partenkirchen","start":1546441200000,"end":1546513200000,"type":5,"state":"Bayern","level":2,"stateShort":"BY","description":"Es tritt mäßiger Frost zwischen -4 °C und -8 °C auf. Vor allem bei Aufklaren über Schnee sinken die Temperaturen auf Werte um -10 °C.","altitudeStart":null,"altitudeEnd":null,"headline":"Amtliche WARNUNG vor FROST","instruction":"","event":"FROST"}],

**Comment by Diginix** [comment]
Für meinen Kreis gibt es aktuell sogar 5 Warnungen und dennoch wird nur der erste Treffer im JSON ausgewertet.
`{"regionName":"Ilm-Kreis","start":1552258800000,"end":1552345200000,"type":1,"state":"Thüringen","headline":"Amtliche WARNUNG vor STURMBÖEN","altitudeStart":600,"altitudeEnd":null,"description":"Es treten oberhalb 600 m Sturmböen mit Geschwindigkeiten bis 75 km/h (21m/s, 41kn, Bft 9) anfangs aus westlicher, später aus nordwestlicher Richtung auf.","level":3,"stateShort":"TH","instruction":"ACHTUNG! Hinweis auf mögliche Gefahren: Es können zum Beispiel einzelne Äste herabstürzen. Achten Sie besonders auf herabfallende Gegenstände.","event":"STURMBÖEN"},{"regionName":"Ilm-Kreis","start":1552330800000,"end":1552374000000,"type":6,"state":"Thüringen","headline":"Amtliche WARNUNG vor GLÄTTE","altitudeStart":null,"altitudeEnd":null,"description":"Es muss mit Glätte durch verbreitet überfrierende Nässe sowie geringfügigen Schneefall gerechnet werden.","level":2,"stateShort":"TH","instruction":"","event":"GLÄTTE"},{"regionName":"Ilm-Kreis","start":1552318260000,"end":1552352400000,"type":3,"state":"Thüringen","headline":"Amtliche WARNUNG vor LEICHTEM SCHNEEFALL","altitudeStart":null,"altitudeEnd":null,"description":"Es tritt im Warnzeitraum leichter Schneefall mit Mengen zwischen 5 cm und 10 cm auf. Verbreitet wird es glatt.","level":2,"stateShort":"TH","instruction":"","event":"LEICHTER SCHNEEFALL"},{"regionName":"Ilm-Kreis","start":1552251600000,"end":1552345200000,"type":1,"state":"Thüringen","headline":"Amtliche WARNUNG vor WINDBÖEN","altitudeStart":null,"altitudeEnd":null,"description":"Es treten Windböen mit Geschwindigkeiten bis 60 km/h (17m/s, 33kn, Bft 7) anfangs aus westlicher, später aus nordwestlicher Richtung auf. In Schauernähe muss mit Sturmböen bis 70 km/h (20m/s, 38kn, Bft 8) gerechnet werden.","level":2,"stateShort":"TH","instruction":"","event":"WINDBÖEN"},{"regionName":"Ilm-Kreis","start":1552338000000,"end":1552370400000,"type":5,"state":"Thüringen","headline":"Amtliche WARNUNG vor FROST","altitudeStart":null,"altitudeEnd":null,"description":"Vor allem bei Aufklaren tritt leichter Frost bis -2 °C auf. Über Schnee sinken die Temperaturen auf Werte bis -4 °C.","level":2,"stateShort":"TH","instruction":"","event":"FROST"}`

**Comment by GermanBluefox** [comment]
F5 - Browser refresh could solve the problem
