### ISSUE TITLE
TS Umrechnung fehlerhaft

### ISSUE THREAD

**Issue by Parodontitis** [ioBroker/ioBroker.dwd#26]
Datenpunkte: dwd.0.warning.begin und dwd.0.warning.start
Timestamp: 1552149224152
Wird in DWD Datenpunkt als: "Tue Sep 03 2019 18:46:00 GMT+0200 (Mitteleuropäische Sommerzeit)" angezeigt.
ist:  "Tue **Sep 03** 2019 18:46:00 GMT+0200 (Mitteleuropäische Sommerzeit)" 
soll: "Sa **Mar 09** 2019 18:46:00 GMT+0200 (Mitteleuropäische Sommerzeit)"

Hier scheint die Reihenfolge DDMM und MMDD nicht zu stimmen.

**Comment by Diginix** [comment]
Kann ich mit Version 2.4.3 bestätigen.

**Comment by Diginix** [comment]
Der Bug hat glaube nichts mit dem Adapter zu tun.
In ioBroker kann man im admin Bereich ein globales Datumsformat festlegen (z.B. DD.MM.YYYY).
Adapter können dann im JS eine "formatdate" Funktion nutzen, was im DWD auch gemacht wird.
Somit landet im Datenpunkt kein timestamp mehr sondern eben DD.MM.YYYY. Die Ausgabe im Objektbereich von ioBroker (admin) kann mit diesem Format aber nicht umgehen weil von MM.DD.YYYY ausgegangen wird.
Ich habe im DWD Adapter nun die vorherige Formatierung/Konvertierung deaktiviert und lasse mir direkt den timestamp in den Datenpunkt schreiben. Dieser wird vom admin Adapter ebenso zu einem korrekten Datum umgewandelt. Außerdem kann ein timestamp in VIS, Skripten usw. universeller weiterverarbeitet werden. Ich werde das mal als Pull Request einreichen.

**Comment by joergzdarsky** [comment]
Bei mir zeigt der Adapter im "begin" und "end" Datenpunkt leider nur noch "Invalid Date" als Wert an. Ich vermute auch nicht dass das etwas mit dem ioBroker Settings Datenformat zu tun hat?

**Comment by GermanBluefox** [comment]
Please test 2.4.6

**Comment by Diginix** [comment]
Bei mir passt es jetzt wieder. Ist ja auch nur der original DWD timestamp als Wert oder?
Nur der Datentyp von begin und end ist noch string und könnte number sein.

**Comment by GermanBluefox** [comment]
> Bei mir passt es jetzt wieder. Ist ja auch nur der original DWD timestamp als Wert oder?
> Nur der Datentyp von begin und end ist noch string und könnte number sein.

Das kann man manuell korrigieren. Alle neu angelegten Instanzen werden schon "number" haben.

**Comment by Diginix** [comment]
Nein, ist auch in der aktuelle GIT io-package.json ein string. Aber es funktioniert ja auch so.
![image](https://user-images.githubusercontent.com/39678667/75258865-644c3800-57e7-11ea-9bdd-a710980cf6b6.png)
