### ISSUE TITLE
Adapter gives lots of "error" "Not exists" when running

### ISSUE THREAD

**Issue by buanet** [ioBroker/ioBroker.dwd#28]
Hi,

my dwd.0 gives lots of "error" "Not exists" in Logfile when running:
![error](https://user-images.githubusercontent.com/16137672/54351748-72de2580-4650-11e9-949a-239c00b9c86d.PNG)

Not sure how this is caused. No additional output in debug-mode. Adapter is working, weather-warnings are up to date.

Adapter-Version is: 2.4.3
JS-Controller: 1.4.2
Node: v8.15.0

best regards,
André

**Comment by GermanBluefox** [comment]
Is the error still there?
