### ISSUE TITLE
Landkreis Wunsiedel  im Fichtelgebirge funktioniert nicht

### ISSUE THREAD

**Issue by Sweatchcuk** [ioBroker/ioBroker.dwd#34]
Hallo,

für den Landkreis Wunsiedel im Fichtelgebirge bekomme ich leider keine Meldungen obwohl auf der DWD Internetseite welche vorhanden sind. Ich hab das mal eine Woche laufen lassen aber es kommt nichts an. 

P.S. Der Alexa DWD Skill liefert die richtigen Meldungen.

Über eine Info würde ich mich freuen.

Danke

**Comment by GermanBluefox** [comment]
Es ist klar, dass man nicht irgendeinen Namen eingeben darf?
Man muss die Namen nehmen, die vorgeschlagen sind: 
![image](https://user-images.githubusercontent.com/4582016/75154139-5a560680-570d-11ea-8a7c-32bfcd26c47f.png)

**Comment by Sweatchcuk** [comment]
Hallo Bluefox,

das ist klar und wurde auch so gemacht. Trotzdem kommt nix an.

Momentan gibt es viele Warnungen für den Kreis Wunsiedel, ist also leicht
nachvollziehbar.

Hier ist noch ein Bug drin. Mit meinem HM Script funktioniert es, würde
aber gerne den Adapter nutzen.

Gruß
Sweatchuck

Bluefox <notifications@github.com> schrieb am Mo. 24. Feb. 2020 um 13:55:
