### ISSUE TITLE
Falsches Datum / Monat<>Tag

### ISSUE THREAD

**Issue by jpawlowski** [ioBroker/ioBroker.dwd#35]
Monat und Tag sind irgendwo vertauscht, so dass sowas dabei herauskommt:

![image](https://user-images.githubusercontent.com/75446/71673732-d10ffc80-2d79-11ea-82c2-76e58bcde0e3.png)

Ich gehe mal stark davon aus, dass die Wettermeldung für den heutigen 2. Januar ist (=02.01.2020 = 2020-01-02 =2020/02/01) und nicht für den 1. Februar ;-)

Beim Datumsformat ist darauf zu achten, dass die amerikanische Schreibweise YYYY/TT/MM verwendet werden muss, da sie ansonsten missinterpretiert wird.

**Comment by Hildesen** [comment]
inzwischen wird nur noch "Invalid Date" angezeigt...

**Comment by Diginix** [comment]
Since the changes of @ticaki the begin and end time of a warning has wrong timestamps (1 hour offset) and if it will be converted in scripts there is another offset.
I would prefer if the state objects contains the real timestamp value from the DWD xml without converting it to any human readable date.

main.js line 184+185
`    adapter.setForeignState(channelName + '.begin',         warnObj.start,  true);
    adapter.setForeignState(channelName + '.end',           warnObj.end,    true);
`

Only this leads to a clean and offset-free handling in scripts. The admin view shows human readable dates automatical by itself if a unix timestamp is the real value of a state.
![2020-02-24_dwd_datetime](https://user-images.githubusercontent.com/39678667/75146135-b2cfd880-56fa-11ea-9c42-9b6bd9d2688b.png)
![2020-02-24_dwd_datetime_convert](https://user-images.githubusercontent.com/39678667/75146144-b82d2300-56fa-11ea-9578-84ac27b45608.png)
![2020-02-24_dwd_original](https://user-images.githubusercontent.com/39678667/75146148-bbc0aa00-56fa-11ea-8207-0ca17f58edbc.png)

**Comment by GermanBluefox** [comment]
It would be better to create new issue for UTC time. 
I think I will change it to have a local time of PC in the state.

**Comment by ticaki** [comment]
Den Wert nicht zu konvertieren war mein erster Gedanke, jedoch war er als "String" definiert und das wollte ich ohne Diskussion nicht ändern. 

Die Stings entsprechen (bei mir) der Zeit in der angezeigten Zeitzone. Und der Wert der in Scripten dargestellt wird ist GMT/UTC.

**Comment by GermanBluefox** [comment]
> Since the changes of @ticaki the begin and end time of a warning has wrong timestamps (1 hour offset) and if it will be converted in scripts there is another offset.
> I would prefer if the state objects contains the real timestamp value from the DWD xml without converting it to any human readable date.
> 
> main.js line 184+185
> ` adapter.setForeignState(channelName + '.begin', warnObj.start, true); adapter.setForeignState(channelName + '.end', warnObj.end, true);`
> 
> Only this leads to a clean and offset-free handling in scripts. The admin view shows human readable dates automatical by itself if a unix timestamp is the real value of a state.
> ![2020-02-24_dwd_datetime](https://user-images.githubusercontent.com/39678667/75146135-b2cfd880-56fa-11ea-9c42-9b6bd9d2688b.png)
> ![2020-02-24_dwd_datetime_convert](https://user-images.githubusercontent.com/39678667/75146144-b82d2300-56fa-11ea-9578-84ac27b45608.png)
> ![2020-02-24_dwd_original](https://user-images.githubusercontent.com/39678667/75146148-bbc0aa00-56fa-11ea-8207-0ca17f58edbc.png)

Could it be, that your system timezone is wrong?
![image](https://user-images.githubusercontent.com/4582016/75150426-a0f33300-5704-11ea-91ed-b50c5a839b1c.png)

**Comment by Diginix** [comment]
@GermanBluefox Nein Zeitzone passt im System und ioBroker. Wenn der DWD timestamp als Objektwert genutzt wird, so wie ich es schon seit März 2019 nutze, passen alle Meldungen perfekt so wie sie DWD auch publiziert.
![image](https://user-images.githubusercontent.com/39678667/75150937-d3e9f680-5705-11ea-84f2-f762b2e01c7a.png)

**Comment by ticaki** [comment]
Hm, bei mir werden die Warnung alle im selben Format ausgegeben:
![Bildschirmfoto 2020-02-24 um 13 21 38](https://user-images.githubusercontent.com/59184294/75152152-b23e3e80-5708-11ea-980a-faf9323b8937.png)

**Comment by Diginix** [comment]
Die Admindarstellung scheint da immer mal fehlerhaft zu sein. Ich habe begin und end der ersten Warnung mal geleert und nach dem erneuten Einlesen von DWD steht nun dort nur der timestamp. Bei allen anderen noch laufenden Warnungen steht der timestamp im Wert, im Admin wird aber ein menschen lesbares Datum angezeigt. Die Admindarstellung ist also nur mit timestamp oder vorkonvertiertem Wert immer mal komisch. Das ist mir egal. Aber die 1h Versatz bei der zweiten Warnung in meinem ersten Screenshot oben ist ein echter Fehler. Da half auch umformatieren nicht mehr. Zumal auch die erste Warnung die 1h Versatz im Wert hat, nur der Adminview diese nicht angezeigt hat. D.h. mit der 2.4.5 haben bei mir alle 1h Versatz. Im Admin sieht man das aber nicht zwangsläufig bei allen direkt. Um diese Willkür in den Griff zu bekommen und meine Skripte weiterhin kompatibel zu halten forke ich die Version nun immer und nutze den DWD XML Wert direkt.

**Comment by GermanBluefox** [comment]
Ich werde das Problem heute Abend korrigieren.

**Comment by ticaki** [comment]
@GermanBluefox  
Ich hab die Art der Übergabe von hier, ist dann eventuell auch falsch:

main.js 245
`adapter.setState('info.lastUpdateCheck', new Date(updateTime - updateTime.getTimezoneOffset() * 60000).toISOString(), true);`

**Comment by GermanBluefox** [comment]
> @GermanBluefox
> Ich hab die Art der Übergabe von hier, ist dann eventuell auch falsch:
> 
> https://github.com/ioBroker/ioBroker.admin/blob/f7c04090a77875104a1db044d12cf7ffb15373f8/main.js#L245

Ja. Es ist falsch. Wird auch korrigiert.
