### ISSUE TITLE
Region Kreis Leer zeigt keine Warnungen

### ISSUE THREAD

**Issue by platoboos** [ioBroker/ioBroker.dwd#38]
Die Region Leer ziegt keine Warnungen. Ich habe auf einen anderen Landkreis gewechselt und dann werden mir Warnungen angezeigt.

**Comment by GermanBluefox** [comment]
Sind vielleicht keine Daten in DWD Dienst dafür hinterlegt?

**Comment by platoboos** [comment]
Doch es sind welche hinterlegt, habe auf DWD nachgeschaut. Wenn ich den Landkreis Emsland nehme dann zeigt er mir auch etwas an. Der Lankkreis grenzt an unseren.
