### ISSUE TITLE
DWD-Widget v2.4.6 shows wrong Date/Time

### ISSUE THREAD

**Issue by Berchemer** [ioBroker/ioBroker.dwd#40]
Updated DWD to v2.4.6.
This is the output of the widget:
![2020-02-25 - 09_12 - DWD - Unbenannt](https://user-images.githubusercontent.com/44316663/75228619-ab6b0680-57b0-11ea-9840-2f06e7ad8852.PNG)
This is the content of the related objects of Warning0:
![2020-02-25 - 09_20 - DWD - Unbenannt](https://user-images.githubusercontent.com/44316663/75228782-fab13700-57b0-11ea-904a-23ebb610c1e3.PNG)
Object 'warning begin' of this Warning0 is 'Mon Feb 24 2020 16:00:00 GMT+0100 (Mitteleuropäische Normalzeit)'
Object 'warning end' of this Warning0 'Tue Feb 25 2020 10:00:00 GMT+0100 (Mitteleuropäische Normalzeit)'

**Comment by GermanBluefox** [comment]
Is it app or cloud or local?

**Comment by Berchemer** [comment]
Sorry... my fault...
After restart of ioBroker, everything is fine!
Issue can be closed :-)

**Comment by Berchemer** [comment]
Sorry but one question left.
Inside the widget now only the date is shown but not the time from and time until.
![2020-02-25 - 17_43 - Unbenannt](https://user-images.githubusercontent.com/44316663/75267487-97e28e80-57f6-11ea-98a4-bfbe4e3b1bb7.PNG)
![2020-02-25 - 17_44 - Unbenannt](https://user-images.githubusercontent.com/44316663/75267495-99ac5200-57f6-11ea-9f6b-824648589918.PNG)

**Comment by Berchemer** [comment]
Sorry but one question left.
Inside the widget now only the date is shown but not the time from and time until.
![2020-02-25 - 17_43 - Unbenannt](https://user-images.githubusercontent.com/44316663/75267487-97e28e80-57f6-11ea-98a4-bfbe4e3b1bb7.PNG)
![2020-02-25 - 17_44 - Unbenannt](https://user-images.githubusercontent.com/44316663/75267495-99ac5200-57f6-11ea-9f6b-824648589918.PNG)

**Comment by Berchemer** [comment]
Now I have two messages with DD:MM HH:MM but the year is missing. Is this correct???
![2020-02-25 - 18_01 - Unbenannt](https://user-images.githubusercontent.com/44316663/75269212-d5481b80-57f8-11ea-9286-2983e92bf30a.PNG)
![2020-02-25 - 18_04 - Unbenannt](https://user-images.githubusercontent.com/44316663/75269532-58697180-57f9-11ea-9c36-f4584e3b322e.PNG)
