### ISSUE TITLE
Lots of errors regarding "lat" not being defined

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.dwd#43]
I see this in the ioBroker logs (output of the docker container):

```
(node:7616) UnhandledPromiseRejectionWarning: ReferenceError: lat is not defined
    at adapter.getForeignObjectAsync.then.sys_conf (/opt/iobroker/node_modules/iobroker.dwd/main.js:260:114)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The stack trace indicates that ioBroker.dwd attempts to read the `lat(itude?)` of some object and that does not exist. I have configured my city and coordinates in the ioBroker main settings.

**Comment by wendy2702** [comment]
Same here. Running iobroker at Proxmox LXC container:

`Apr  4 09:10:00 iobroker bash[126]: 2020-04-04 09:10:00.027  - #033[32minfo#033[39m: host.iobroker instance system.adapter.dwd.0 started with pid 26630
Apr  4 09:10:01 iobroker bash[126]: (node:26630) UnhandledPromiseRejectionWarning: ReferenceError: lat is not defined
Apr  4 09:10:01 iobroker bash[126]:     at adapter.getForeignObjectAsync.then.sys_conf (/opt/iobroker/node_modules/iobroker.dwd/main.js:260:114)
Apr  4 09:10:01 iobroker bash[126]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Apr  4 09:10:01 iobroker bash[126]: (node:26630) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Apr  4 09:10:01 iobroker bash[126]: (node:26630) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Apr  4 09:10:02 iobroker bash[126]: 2020-04-04 09:10:02.628  - #033[32minfo#033[39m: host.iobroker instance system.adapter.dwd.0 terminated with code 0 (NO_ERROR)
`

**Comment by MarkSau** [comment]
same error:
`

dwd.0 | 2020-04-17 13:45:31.087 | error | (32010) ReferenceError: lat is not defined at /opt/iobroker/node_modules/iobroker.dwd/main.js:260:114 at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
dwd.0 | 2020-04-17 13:45:31.083 | error | (32010) uncaught exception: lat is not defined

`
 node: v12.16.2, js-controller: 3.0.11

**Comment by Apollon77** [comment]
Please test 2.4.7
