### ISSUE TITLE
No Data but why?

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/ioBroker.dwd#44]
![image](https://user-images.githubusercontent.com/8565847/79570707-3df59b00-80ba-11ea-950d-663dd0802ae8.png)
![image](https://user-images.githubusercontent.com/8565847/79570745-4e0d7a80-80ba-11ea-9adc-f8828206c86f.png)
![image](https://user-images.githubusercontent.com/8565847/79570760-536ac500-80ba-11ea-8fe5-f734d4f840f5.png)

**Comment by Apollon77** [comment]
Plese test 2.4.7 and make sure coordinates are existing in the iobroker main configuration!
