### ISSUE TITLE
Kein Hintergrund mehr.

### ISSUE THREAD

**Issue by Sooty77** [ioBroker/ioBroker.dwd#48]
Ich habe seit kurzem das Problem in der Version 2.4.10, dass dort nicht mehr die Hintergrundfarbe angezeigt wird.
Heute zum Beispiel gibt es eine Warnung "starke Hitze". Hier sollte der Hintergrund doch lila sein.
Mir wird jedoch nur "starke Hitze" angezeigt. Es scheint als wäre der Hintergrund transparent.
Hat dazu jemand eine Idee?

**Comment by notkom** [comment]
Genau das gleiche Problem habe ich auch feststellen müssen. Meiner Einschätzung nach liegt es an der vorhandenen Hitzemeldung. 
Ich habe folgendes im Adapter getestet:

- Warnregion "Hochsauerlandkreis"
- Derzeit (9.8.2020 14:49 Uhr) vorhanden Warnungen:
-- Amtliche UNWETTERWARNUNG vor SCHWEREM GEWITTER mit EXTREM HEFTIGEM STARKREGEN und HAGEL
-- Amtliche UNWETTERWARNUNG vor SCHWEREM GEWITTER mit HEFTIGEM STARKREGEN und HAGEL
-- Amtliche WARNUNG vor HITZE
- 3 Warnungen im Adapter eingestellt

- Unter Objekten liefert er nur die Hitzewarnung. Keine weiteren.
- Warning severity = 49
- Kein Hintergrund

- Wird das Warning severity von Hand auf 1, 2, 3 oder 4 geändert ist sofort wieder der passende Hintergrund vorhanden.

**Comment by AndreasExner** [comment]
Die dwd.html verwertet severity nur bis 19.

**Comment by Homoran** [comment]
DWD hat neue Kategorien eingeführt: Level 50 - starke Hitze und Level 51 - extreme Hitze
Diese müssen noch in den Adapter eingepflegt werden

**Comment by AndreasExner** [comment]
@Homoran, die neue dwd.html funktioniert (einmal vis neu starten). Danke.

**Comment by notkom** [comment]
Ich habe den Adapter "vis" sowie den Raspi worauf die VIS läuft, neugestartet. Beides führte nicht zum Erfolg.

Ich habe weiterhin kein Hintergrund bei einem Warning severity = 49

@Homoran 
Bei mir ist "starke Hitze" Warning severity 49 und nicht 50.

**Comment by AndreasExner** [comment]
@notkom, die geänderte Datei ist noch nicht im aktuellen Release. Die musst Du von Hand rein kopieren.

**Comment by notkom** [comment]
Ich gehe davon aus, dass ich zu einfach denke :-)

Ich habe von Github den zip-Datei runtergeladen und entpackt. Dann habe ich den Inhalt aus dem Ordner "widgets" mit Filezilla nach "/opt/iobroker/iobroker-data/files/vis/widgets" kopiert und die alten Daten überschrieben. 

Danach den VIS-Adapter neugestartet und die View aktualisiert. Was soll ich sagen, bei mir bleibt der Hintergrund weg.

Mit Sicherheit habe ich etwas falsch gemacht. Was ist es? :-)

**Comment by AndreasExner** [comment]
Die Datei gibt es 3x (pfade könnten etwas anders sein, da iobroker bei mir als Docker Container läuft):

/opt/iobroker-data/files/vis/widgets/ (Änderungen hier bringen gar nix, die Datei wird anscheinend bei jeder Ausführung der Instanz überschrieben)

/opt/node_modules/iobroker.dwd/widgets/
/opt/node_modules/iobroker.vis/www/widgets/

Ich hab nicht weiter rumprobiert welche der Beiden jetzt entscheidend ist und alle drei überschrieben.

**Comment by notkom** [comment]
/opt/iobroker/node_modules/iobroker.dwd/widgets

Diesen Ordner mit dem Ordner Widgets ersetzen, dann funktioniert es.

@AndreasExner 
Danke. Funktioniert prima.

**Comment by Sooty77** [comment]
Ich habe eben versucht die Datei auszutauschen.
Leider ist mir das auf Grund fehlender Zugriffsrechte nicht gelungen.
Ich habe den iob per Konsole gestoppt und dann versucht die Datei über ftp auszutauschen.
Hat evtl. jemand einen Tip für mich?

**Comment by notkom** [comment]
Ich muss gestehen, dass ich das ohne iobroker "stop" gemacht habe. Ich habe die Datei einfach mit Filezilla ausgetausch bzw. überschrieben. Vielleicht versuchst du mal filezilla?

**Comment by Sooty77** [comment]
Ich habe es jetzt hinbekommen.
Ich habe mich als root in Filezilla angemeldet.
Dann ging es. 
Jetzt ist wieder alles schick.

**Comment by notkom** [comment]
Sorry, habe ich vergessen zu erwähnen. Ich war auch als root drin.
Super!
