### ISSUE TITLE
 ECONNREFUSED 141.38.3.62:80

### ISSUE THREAD

**Issue by oke24** [ioBroker/ioBroker.dwd#50]
Hallo, ich erhalte seit einigen Stunden/Tagen alle 60 sec. einen Verbindungsfehler  ECONNREFUSED 141.38.3.62:80 zum DWD-Server

```
dwd.0 | 2020-10-04 11:56:04.212 | info | (10598) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
dwd.0 | 2020-10-04 11:56:03.112 | error | (10598) Empty or invalid JSON: Cannot read JSON file: Error: connect ECONNREFUSED 141.38.3.62:80
dwd.0 | 2020-10-04 11:56:02.746 | info | (10598) starting. Version 2.4.10 in /opt/iobroker/node_modules/iobroker.dwd, node: v10.22.0, js-controller: 3.1.6

```
Entsprechend werden die Wetterdaten nicht mehr aktualisiert. VG, ok

**Comment by Apollon77** [comment]
The IP named there is the one from dwd.de . Please try if "curl http://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json" or "wget http://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json" works from the iobroker host. If not you need to check network there

**Comment by oke24** [comment]
Thank you very much ! Indeed, it was a router config problem.
