### ISSUE TITLE
Warning Objekts Nr 1+2 are not created by adapter

### ISSUE THREAD

**Issue by Berchemer** [ioBroker/ioBroker.dwd#51]
In den Adaptereinstellungen können die Anzahl der Warnmeldungen ausgewählt werden.
Bei nur einer Warnung [dwd.0.warning] und 4 Warnungen [dwd.0.warning3], 5 Warnungen [dwd.0.warning4] und 6 Warnungen [dwd.0.warning5] werden auch die Objekte-Ordner und Unterobjekte innerhalb von ioBroker generiert.
Wähle ich jedoch 2 oder 3 Warnungen, werden die Ordner [dwd.0.warning1] und [dwd.0.warning2] nicht angelegt.
Ist mir erst bei einer Neuinstallation aufgefallen, weil wohl in der alten Installation möglicherweise aus einer alten Adapterversion die [dwd.0.warning1] und [dwd.0.warning2] schon existieren. Meine nicht, dass ich sie selber angelegt hätte.

**Comment by Berchemer** [comment]
Kann hier bei Neuinstallationen mit v2.4.10 nicht mehr nachvollzogen werden. War wahrscheinlich eher Fehlalarm.

**Comment by Tronje-the-Falconer** [comment]
Bei mir werden die beiden Datenkanäle mit Version 2.5.1 nicht erzeugt. Ich habe schon mehreres Probiert. mit Adapter löschen, Neuinstallation etc.


DebugLog:

dwd.0 | 2020-12-04 07:21:37.937 | info | (11095) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
dwd.0 | 2020-12-04 07:21:37.936 | debug | (11095) Plugin sentry destroyed
dwd.0 | 2020-12-04 07:21:37.929 | debug | (11095) Add warning "dwd.0.warning9":
dwd.0 | 2020-12-04 07:21:37.927 | debug | (11095) Add warning "dwd.0.warning8":
dwd.0 | 2020-12-04 07:21:37.925 | debug | (11095) Add warning "dwd.0.warning7":
dwd.0 | 2020-12-04 07:21:37.923 | debug | (11095) Add warning "dwd.0.warning6":
dwd.0 | 2020-12-04 07:21:37.921 | debug | (11095) Add warning "dwd.0.warning5":
dwd.0 | 2020-12-04 07:21:37.919 | debug | (11095) Add warning "dwd.0.warning4":
dwd.0 | 2020-12-04 07:21:37.917 | debug | (11095) Add warning "dwd.0.warning3":
dwd.0 | 2020-12-04 07:21:37.914 | debug | (11095) Add warning "dwd.0.warning":
dwd.0 | 2020-12-04 07:21:37.912 | debug | (11095) Add warning "dwd.0.rainradar.Forecast_3h": 2020-12-03T19:00:00.000Z
dwd.0 | 2020-12-04 07:21:37.910 | debug | (11095) Add warning "dwd.0.rainradar.Current": 2020-12-03T17:00:00.000Z
dwd.0 | 2020-12-04 07:21:37.216 | info | (11095) starting. Version 2.5.1 in /opt/iobroker/node_modules/iobroker.dwd, node: v12.19.0, js-controller: 3.1.6
dwd.0 | 2020-12-04 07:21:36.923 | debug | (11095) Plugin sentry Initialize Plugin (enabled=true)

**Comment by ds-1982** [comment]
@Apollon77 
Ich habe plötzlich auch das Problem. Habe mein System auf einem Pi4 neu aufgesetzt (bisher Pi3) und ein Backup eingespielt.

Lösche und erstelle ich eine neue Instanz werden alle Objekte korrekt angelegt und auch angezeigt, wenn entsprechende Warnungen vorliegen. Werden die Werte dann per Cron aktualisiert, verschwinden die  Objekte-Ordner und Unterobjekte dwd.0.warning1 und dwd.0.warning2. Auch die Objekte unter dwd.0.warning werden dann nicht mehr aktualisiert.

**Comment by Berchemer** [comment]
Nachdem ich den Beitrag von ds-1982 las, habe ich bei mir und einer recht frischen Installation nachgeschaut. Am Anfang waren alle Objekte vorhanden. Nun muss ich feststellen, dass tatsächlich 1 und 2 auch bei mir wieder verschwunden sind. Und aktualisiert werden die vorhandenen Objekte auch nicht mehr, obwohl Meldungen vorliegen müssten.

**Comment by Apollon77** [comment]
Hat jemand mal ein Debug Log bitte?

**Comment by Apollon77** [comment]
Ok, machmer anders: Ich habe Github version mit Debug gespickt ... bitte von Github installieren und dann log posten hier - bitte log NICHT aus Admin, sondern Logfile auf Platte!

**Comment by ds-1982** [comment]
Hoffe ich habe alles richtig gemacht.
- Adapter von Github neu installiert
- neu Instanz angelegt (Objekte werden korrekt angelegt)
- Instant angehalten und neu gestartet (Objekte dwd.0.warning1 verschwunden)

[Log.txt](https://github.com/ioBroker/ioBroker.dwd/files/5714425/Log.txt)

**Comment by Berchemer** [comment]
Bin wohl ähnlich vorgegangen, wie mein Vorredner.

- Instanz von DWD gestoppt
- Instanz von DWD gelöscht
- DWD-Adapter gelöscht
- von Github über die Katze und dem Dropdownfeld DWD ausgewählt
- Version 2.51 von Github neu installiert. Dabei Debugausgabe ausgewählt
- nach Installation gab es zunächst natürlich nur warning unter Objekte
- Kreis und Anzahl der Warnungen auf 6 in den Einstellungen gesetzt
- es existieren alle Warnungen (warning, warning1,warning2,warning3,warning4,warning5)
- DWD startet danach neu und warning1 und warning 2 sind verschwunden

Inhalte in warning unter Objekte kann ich nicht checken, weil es derzeit keine Warnungen für meinen Kreis gibt

Logauszug ist angehängt.
[iobroker.2020-12-18.log](https://github.com/ioBroker/ioBroker.dwd/files/5714931/iobroker.2020-12-18.log)

**Comment by Apollon77** [comment]
@ds-1982 @Berchemer  Leider kein Debug Log ... Admin - Instanzen - Expertenmodus - Spalte Logstufe

**Comment by ds-1982** [comment]
@Apollon77  Bitteschön

[iobroker.2020-12-23.log](https://github.com/ioBroker/ioBroker.dwd/files/5733626/iobroker.2020-12-23.log)

**Comment by Berchemer** [comment]
Uuppss...

Dann jetzt nochmals nicht nur mit "debug" sondern "silly"-Einstellung der Protokollierung.

Zur Erklärung diesmal:
Ich habe die Adapter nicht erneut gelöscht und neu installiert sondern...
- DWD-Adapter deaktiviert
- eine vorhandene DVD-Objekte-json eingelesen, in welcher auch warning1 und2 vorhanden sind
- den Adapter erneut gestartet und es wird sichtbar, dass warning1 und 2 gelöscht werden

Sollte "silly" falsch gewesen sein, wiederhole ich auch gerne mit nur "debug"-Protokollierung :-)
Und...
 - Redis benutze ich derzeit noch nicht und habe auch keine diesbezüglichen Einstellungen vorgenommen. Scheint eine Startartroutine vom dwd-Adapter zu sein.

Hier das LOG:
[iobroker.2020-12-23.log](https://github.com/ioBroker/ioBroker.dwd/files/5733944/iobroker.2020-12-23.log)

**Comment by Berchemer** [comment]
Ach ja und noch etwas...
Obwohl, wie im Log sichtbar, eine Warnung existiert, wird diese nicht in "warning" eingetragen.

**Comment by Apollon77** [comment]
> 2020-12-23 07:16:40.674  - [34mdebug[39m: dwd.0 (16824) Existing Channels: ["dwd.0.warning","dwd.0.rainradar.Current","dwd.0.rainradar.Forecast_3h","dwd.0.warning3","dwd.0.warning2","dwd.0.warning1"]

hehe ... die rainrada CHannelsn sind in den check nach Warnungen reingerutscht ...

Bitte nochmal GitHub version installieren und nochmal log posten

**Comment by Berchemer** [comment]
@Apollon77: Ok. Danke für die Nachtarbeit!

- alte Instanz gelöscht
- DWD von Github neu installiert. Als Versionsnummer wird immer noch 2.5.1 angegeben
- neue Instanz installiert
- in Einstellungen den Kreis, das Land und 6 Warnungen eingestellt
- Warning1 und 2 existieren auch weiterhin, trotz Neustart des DWD :-)

Scheint momentan soweit gelöst für mich. Werde mal schauen, was passiert, wenn mehr als eine Warnung kommt. Sollte aber wahrscheinlich erledigt sein, weil Du wohl den Fehler gefunden hast ;-) 

[iobroker.2020-12-24.log](https://github.com/ioBroker/ioBroker.dwd/files/5739151/iobroker.2020-12-24.log)

**Comment by Apollon77** [comment]
Super, naja Kids müssen halt im Bett sein bevor man sinnvoll arbeiten kann ;-))

Und super das es das scheinbar war. Das debug log hat's gebracht.

**Comment by Apollon77** [comment]
Kommt später als update offiziell

**Comment by ds-1982** [comment]
@Apollon77 
Bei mir sieht auch alles gut aus, funktioniert. Danke!
