### ISSUE TITLE
Landkreis Wunsiedel funktioniert nicht

### ISSUE THREAD

**Issue by Sweatchuck** [ioBroker/ioBroker.dwd#54]
Es sind Warnungen vorhanden, werden aber in ioBroker nicht angezeigt. Andere Regionen funktionieren einwandfrei.

**Comment by kortos** [comment]
Kreis Ludwigsburg funktioniert auch nicht mehr.

**Comment by kortos** [comment]
In der JSON-Datei ist ein Eintrag für den Landkreis Ludwigsburg enthalten:

https://www.dwd.de/DWD/warnungen/warnapp/json/warnings.json

**Comment by Sweatchuck** [comment]
Anbei der Eintrag in der JSON-Datei. 

regionName":"Kreis Wunsiedel i. Fichtelgebirge","end":1606384800000,"start":1606359660000,"type":4,"state":"Bayern","level":2,"description":"Es tritt gebietsweise Nebel mit Sichtweiten unter 150 Metern auf.","event":"NEBEL","headline":"Amtliche WARNUNG vor NEBEL","instruction":"","stateShort":"BY","altitudeStart":null,"altitudeEnd":null},{"regionName":"Kreis Wunsiedel i. Fichtelgebirge","end":1606384800000,"start":1606327200000,"type":5,"state":"Bayern","level":2,"description":"Es tritt leichter Frost bis -5 °C auf.","event":"FROST","headline":"Amtliche WARNUNG vor FROST","instruction":"","stateShort":"BY","altitudeStart":null,"altitudeEnd":null}],"109180000":

Leider kein Eintrag im Adapter...

**Comment by Apollon77** [comment]
Kann es sein das die Namen im JSON geändert wurden? habt Ihr zB wirklich "Kreis Wunsiedel i. Fichtelgebirge" in der Konfig? Der Adapter macht einen "exact match" was den regionName angeht

**Comment by kortos** [comment]
Also in meinem Fall habe ich in der Konfig "Kreis Ludwigsburg" und im json finde ich hierzu auch einen Eintrag. Er legt aber trotzdem nichts an. Im Log ist nichts zu finden...

**Comment by Sweatchuck** [comment]
Hallo Apollon77,

dein Tipp hats echt gebracht. Problem war, dass beim Dropdown nur Kreis Wunsiedel ausgewählt werden kann. Es muss aber Kreis Wunsiedel i. Fichtelgebirge heißen. Ich danke dir!! Gruß
Sweatchuck

**Comment by kortos** [comment]
Hallo zusammen,
ich habe bei mir jetzt mal ebenfalls den von Dir @Sweatchuck benannten Landkreis eingegeben, was auch nicht funktionierte. Also liegts nicht am Adapter sondern an meiner Umgebung. Nach dem Löschen und neu installieren des Adapters hat bei mir jetzt der Landkreis Ludwigsburg auch funktioniert. Was auch immer da war, ich glaube wir können das Issue schließen. :-) Danke @Apollon77  :-)
