### ISSUE TITLE
Warning1 und 2 werden nicht erzeugt

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [ioBroker/ioBroker.dwd#56]
**Describe the bug**  
Bei mir werden die beiden Datenkanäle mit Version 2.5.1 nicht erzeugt. Ich habe schon mehreres Probiert. mit Adapter löschen, Neuinstallation etc.

DebugLog:

dwd.0 | 2020-12-04 07:21:37.937 | info | (11095) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
dwd.0 | 2020-12-04 07:21:37.936 | debug | (11095) Plugin sentry destroyed
dwd.0 | 2020-12-04 07:21:37.929 | debug | (11095) Add warning "dwd.0.warning9":
dwd.0 | 2020-12-04 07:21:37.927 | debug | (11095) Add warning "dwd.0.warning8":
dwd.0 | 2020-12-04 07:21:37.925 | debug | (11095) Add warning "dwd.0.warning7":
dwd.0 | 2020-12-04 07:21:37.923 | debug | (11095) Add warning "dwd.0.warning6":
dwd.0 | 2020-12-04 07:21:37.921 | debug | (11095) Add warning "dwd.0.warning5":
dwd.0 | 2020-12-04 07:21:37.919 | debug | (11095) Add warning "dwd.0.warning4":
dwd.0 | 2020-12-04 07:21:37.917 | debug | (11095) Add warning "dwd.0.warning3":
dwd.0 | 2020-12-04 07:21:37.914 | debug | (11095) Add warning "dwd.0.warning":
dwd.0 | 2020-12-04 07:21:37.912 | debug | (11095) Add warning "dwd.0.rainradar.Forecast_3h": 2020-12-03T19:00:00.000Z
dwd.0 | 2020-12-04 07:21:37.910 | debug | (11095) Add warning "dwd.0.rainradar.Current": 2020-12-03T17:00:00.000Z
dwd.0 | 2020-12-04 07:21:37.216 | info | (11095) starting. Version 2.5.1 in /opt/iobroker/node_modules/iobroker.dwd, node: v12.19.0, js-controller: 3.1.6
dwd.0 | 2020-12-04 07:21:36.923 | debug | (11095) Plugin sentry Initialize Plugin (enabled=true)

**Comment by Tronje-the-Falconer** [comment]
Noch ein weiterer Test mit einer bisher unbenutzten Instanzzahl (3). Hier habe ich festgestellt, das beim ersten Start 1 und 2 erzeugt und auch abgerufen werden, aber nach einem Wechsel auf einen anderen Tab und wieder zurück auf Objekte, sind die beiden warnings weg.

**Comment by ds-1982** [comment]
Hier auch. Habe mein System auf einem Pi4 neu aufgesetzt (bisher Pi3) und ein Backup eingespielt.

Lösche und erstelle ich eine neue Instanz werden alle Objekte korrekt angelegt und auch angezeigt, wenn entsprechende Warnungen vorliegen. Werden die Werte dann per Cron aktualisiert, verschwinden die Objekte-Ordner und Unterobjekte dwd.0.warning1 und dwd.0.warning2. Auch die Objekte unter dwd.0.warning werden dann nicht mehr aktualisiert.

**Comment by harrym67** [comment]
Selbiges hier.

**Comment by Apollon77** [comment]
duplicate #51
