### ISSUE TITLE
Systemdatenpunkte

### ISSUE THREAD

**Issue by MCepheus** [ioBroker/ioBroker.dwd#57]
Hi, ich habe mal eine Frage zu den Systemdatenpunkten. Ich meine die Datenpunkte, die in diesem Fall unter system.adapter.dwd.0 liegen. Im speziellen Fall der Punkt "alive" und "connected". Soweit ich das jetzt recherchiert habe, zeigt der Punkt "alive" an, ob der Adapter aktiv geschaltet ist. Der Punkt "connected" ob sich der Adapter innerhalb der letzten 30 sek gemeldet hat.
Ich verwende die Punkte in meiner VIS normalerweise in folgender Art und Weise:

"Alive" habe ich mit einem Schalter verknüpft, der es mir erlaubt den Adapter aktiv auszuschalten. Das hat den gleichen Effekt als würde ich ihn im ioBroker deaktivieren.
"Connectet" nutze ich über ein Binding, das mir in der VIS den Hintergrund des dazugehörigen Icons ändert, wenn der Datenpunkt auf "true" steht. (Bei "true" auf grün, sonst auf rot.)

Bei den meisten Adaptern funktioniert das prima. Hier kommen aber einige Dinge zusammen, die das nicht funktional machen.
Zum Einen wird der Adapter über den Datenpunkt "alive" erst einmal als "false" angezeigt, auch wenn er eigentlich aktiv ist. Erst wenn der Cron-Job alle 5 Minuten startet ändert er sich kurz auf "true" bis alles abgearbeitet wurde um dann wieder auf "false" zu wechseln. Problem dabei, mein Schalter wechselt mit. Von aus, nach ein, zu aus. Ich kann in dem Fall nicht erkennen, ob ich den Adapter manuell ausgeschaltet haben (dann würde auch der Cron-Job nicht merh funktionieren) oder ob der Adapter nur auf den nächsten Start über den Cron-Job wartet.
Zum Anderen habe ich mit dem Binding ein Problem. Startet der Cron-Job, wechselt der Datenpunkt "connected" nach true. Der Hintergrund meines Icons wird grün. Soweit so gut. Der Datenpunkt wechselt nach Beenden des Adapters aber nicht wieder zu "false" und wird nach den 30 sek nur "ausgeblendet". Das führt dazu, dass mein Iconhintergrund grün bleibt, obwohl der Adapter nicht aktiv ist.

Müsste es daher nicht eher so sein, dass der Datenpunkt "alive" immer auf "true" steht solange der Adapter im ioBroker auch eingeschaltet ist, unabhängig ob Cone-Job oder nicht? Und müsste der Datenpunkt "connected" dann nicht eher die Aktivität anzeigen, also "true" bei gestartetem Cron-Job und "false" wenn der Adapter seinen Job beendet hat und auf die nächste Aktivierung über Cron wartet?

Ich kenne mich da nicht aus und weiß nicht, wie das alles impementiert ist und ob man das änder kann bzw. ändern sollte. Bei den meisten anderen Adaptern scheint es aber so zu funktionieren und ich kann meine oben beschriebene Vorgehensweise nutzen. 

Viele Grüße!

**Comment by Apollon77** [comment]
Der Alive State führt quasi ein doppelleben :-)
Lesend zeigt er an ob der Adapter gerade läuft == gestartet ist/sein sollte.

**Comment by Apollon77** [comment]
Da ist aber generell ein js.controller Thema
