### ISSUE TITLE
Update region list

### ISSUE THREAD

**Issue by Maverick78de** [ioBroker/ioBroker.dwd#65]
Seit einigen Wochen gibt es keine Updates mehr für den Kreis "Neustadt a.d. Aisch - Bad Windsheim" 
Warnungen in der Android App "WarnWetter" gibt es aber
Im Debug Mode sehe ich zwar Daten kommen, aber die Objekte werden nicht aufgefüllt.

DWD Adapter 2.5.2

**Comment by Maverick78de** [comment]
Update, die Updates für den Landkreis gehen seit dem 19.10.2020 nicht mehr.

**Comment by Apollon77** [comment]
Ist der Name korrekrt? Ich glaueb es wurden bei DWD mal Namen angepasst

**Comment by Maverick78de** [comment]
Der Name stammt aus der Auswahlliste.

**Comment by Apollon77** [comment]
Dann bitte mit aktueller Latest Version mal Debug log senden (Instanzen - Expertenmodus - Spalte "Logstufe")

**Comment by Maverick78de** [comment]
Anbei das log
Aus dem Json kann man den Kreis mit der Warnung heraus lesen, jedoch wird nichts in die Objekte geschrieben.

[dwd.log](https://github.com/ioBroker/ioBroker.dwd/files/5862181/dwd.log)

**Comment by Maverick78de** [comment]
gleiches mit der latest 2.7.2
[dwd2.7.2.log](https://github.com/ioBroker/ioBroker.dwd/files/5862221/dwd2.7.2.log)

**Comment by Apollon77** [comment]
Also im Datenfile heisst die Region "Kreis Neustadt a.d. Aisch-Bad Windsheim" und es muss exakt passen. Geht das?

**Comment by Maverick78de** [comment]
Ok mit "Kreis Neustadt a.d. Aisch-Bad Windsheim" geht es, in der Auswahlliste steht "Kreis Neustadt a.d. Aisch - Bad Windsheim"

**Comment by Apollon77** [comment]
Jupp, muss schauen das ich den Eintrag fixe
