### ISSUE TITLE
DWD-Adapter lässt iobroker objects.json im Intervall speichern

### ISSUE THREAD

**Issue by Wildbill-Z** [ioBroker/ioBroker.dwd#66]
Wenn man den DWD-Adapter per cron intervallweise starten lässt, so wird von iobroker jedes Mal die komplette objects.json neu gespeichert, was, gerade auf SSD, die Anzahl der gespeicherten Daten stark ansteigen lässt und die Haltbarkeit auf längere Zeit reduziert.
Möglicherweise liesse sich das ja umgehen, wenn der Adapter je nach Anzahl der anzuzeigenden Meldungen eine feste Anzal an Datenpunkten leer erstellt und diese dann nur gefüllt werden, wenn neue Daten anliegen. So würde die objects.json hier nicht geändert und nur die states gespeichert, was in Verbindnung mit states in redis die Schreiblast abermals reduzieren würde?!

Gruss, Jürgen

**Comment by Apollon77** [comment]
Das Problem hier ist das der Adapter nicht weiss was schon da ist, da er im Schedule läuft. Am Ende ist es das Thema https://github.com/ioBroker/ioBroker.js-controller/issues/764

Im momemtn wäre eine Idee das writeInterval der Objects DB hoch zu setzen was in der iobroker.json Konfiguration geht, aber dann wäre bei einem harten crash ggf mehr verloren ...

Das ist so ein Thema und wenn eher Controller Thema, daher schiesse ich hier
