### ISSUE TITLE
"end" und "start" Datenpunkte liefern keine validen Timestamps mehr?

### ISSUE THREAD

**Issue by jlegen** [ioBroker/ioBroker.dwd#69]
Hi,
bin auf DWD-Version 2.7.4, leider weiss ich nicht mehr wirklich, seit wann genau ich nun diese Datenpunkte vom DWD Adapter bekomme:

`2021-02-07 17:01:01.277  - ESC[34mdebugESC[39m: dwd.0 (9591) Sorted Warnings: [{"regionName":"Stadt Wuppertal","end":1612717200000,"start":1612684800000,"type":3,"state":"Nordrhein-Westfalen","level":2,"description":...`

Wenn ich die letzten 4 Nullen entferne, stimmt der TS wieder. Derzeit zeigen mir die Dialoge in der Vis (Iqontrol) aber leider nur noch
Beginn: aN.aN.NaN, aN:aN etc.

Bin nicht sicher, ob das tatsächlich an DWD liegt - allerdings war das Update auf 2.7.4 eines der letzten... 
(JS-Controller noch auf 3.1.6, falls das eine Rolle spielt)

Edit: Ok, sehe gerade im Code, dass der Timestamp wohl so aussehen soll, wie hier "gemeldet", also liegt mein Problem wohl an etwas anderem. Ich lass' trotzdem mal offen, in der Hoffnung auf einen hilfreichen Tip! :-)

**Comment by Apollon77** [comment]
Das sind schei9nbar timestamps in millisekunden ... hat sich seit langem nichts daran geändert. 

Um welchen Datenpunkt genau geht es denn? Das log ist ja was ganz anderes

Was sagt der visu dev dazu?

**Comment by jlegen** [comment]
Ja, hab‘ ich inzwischen auch gelernt, und auch, dass dieses Format im DWD-Adapter schon vor längerer Zeit eingeführt wurde.
DIe DPs, die ich in Iqontrol nutze, und die merkwürdigerweise bis gestern funktionierten sind
dwd.0.warning.begin
dwd.0.warning.end
Nachdem ich gestern dann einfach weitere DPs in der Ansicht hinzugefügt hatte
dwd.0.warning1.begin
dwd.0.warning1.end
erscheinen jetzt nur noch die o.g. Platzhalter (a.N).
Werde noch versuchen, das im Iqontrol irgenwie zu debuggen, ansonsten frag‘ ich mal im Iqontrol-Thread...
