### ISSUE TITLE
Debug-Level-Einstellung wird ignoriert

### ISSUE THREAD

**Issue by invidianer** [ioBroker/ioBroker.dwd#75]
**Describe the bug**  
Trotz Einstellen auf "warn" werden im Log auch "info"-Zeilen ausgegeben.

**To Reproduce** 
Gehe zu "Instanzen", "dwd.0", "Log-Stufe" auf "warn"

**Expected behavior**  
Unter "Log" sollten keine Meldungen der Stufe "info" mehr erscheinen.

**Screenshots & Logfiles**  
Log:
2021-03-07 14:00:00.081 - info: host.raspberrypi instance system.adapter.dwd.0 started with pid 6029
2021-03-07 14:00:08.649 - info: host.raspberrypi instance system.adapter.dwd.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)

**Versions:**  
 - Adapter version:  2.7.5
 - JS-Controller version: 3.2.16
 - Node version: 12.21.0
 - Operating system: macOS

**Additional context**

**Comment by Apollon77** [comment]
These logs are generated from js-controller and so are not subject to loglevel from the respective adapter itself
