### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by Siggi0904** [ioBroker/ioBroker.dwd#76]
Bei mir laufen seit ein paar Stunden parsing Fehler der json Datei auf.
Gibt es dazu Infos?

Fehler:
`dwd.0 | 2021-03-27 16:15:08.026 | error | (1548) Empty or invalid JSON: Cannot parse JSON file: SyntaxError: Unexpected token p in JSON at position 263503`

**Comment by Apollon77** [comment]
Naja, ich würde tippen das das FIle auf dem dwd Server kaputt ist. Besteht das Problem immer noch?

**Comment by Siggi0904** [comment]
Ja, hat sich wieder erledigt. Fehler erscheint nicht mehr.
Dann mache ich hier wieder zu.

**Comment by Siggi0904** [comment]
Also ich habe den Fehler nun fast täglich mindestens einmal im log liegen.
Kann man sowas fangen oder mal schauen, wo das Problem seitens DWD oder der IOBroker Auswertung liegt?

Danke.

**Comment by Apollon77** [comment]
Naja was soll der Adapter denn tun wenn das JSON falsch ist? es ist ein Schedule adapter, also loggt er den Fehler und beendet sich und aktualisiert nichts. und beim nächsten lauf wird es wieder versucht

**Comment by Siggi0904** [comment]
ja, stimmt. Da kann man nichts machen, wenn die Quelle die Fehler erzeugt.
