### ISSUE TITLE
no existing object warning in log

### ISSUE THREAD

**Issue by Qube2org** [ioBroker/ioBroker.dwd#84]
**Describe the bug**  

no existing object warning in log.

**To Reproduce**  

in log of Iobroker you find many issue indicating a no existing object, like:

dwd.0 | 2021-05-13 21:51:43.528 | warn | (3649958) State "dwd.0.warning2.map" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
dwd.0 | 2021-05-13 21:51:43.517 | warn | (3649958) State "dwd.0.warning2.type" has no existing object, this might lead to an error in future versions
dwd.0 | 2021-05-13 21:51:43.514 | warn | (3649958) State "dwd.0.warning2.level" has no existing object, this might lead to an error in future versions
dwd.0 | 2021-05-13 21:51:43.506 | warn | (3649958) State "dwd.0.warning1.map" has no existing object, this might lead to an error in future versions
dwd.0 | 2021-05-13 21:51:43.495 | warn | (3649958) State "dwd.0.warning1.type" has no existing object, this might lead to an error in future versions
dwd.0 | 2021-05-13 21:51:43.493 | warn | (3649958) State "dwd.0.warning1.level" has no existing object, this might lead to an error in future versions

**Expected behavior**  

no warning about no existing objects, so all  states need to have the right object type.

**Versions:**  
 - Adapter version: 2.7.5
 - JS-Controller version: 3.3.9
 - Node version: v14.17.0
 - Operating system: Ubuntu 20.04.2 LTS

**Comment by GermanBluefox** [comment]
please test 2.7.6
