### ISSUE TITLE
Warning after js-controller 3.3 Update

### ISSUE THREAD

**Issue by n3ucr0n** [ioBroker/ioBroker.dwd#86]
After updateting to js-controller 3.3 i got this messages at the log:

dwd.0 | 2021-05-27 10:35:02.948 | info | State value to set for "dwd.0.warning3.severity" has to be type "number" but received type "string"
-- | -- | -- | --
dwd.0 | 2021-05-27 10:35:02.937 | info | State value to set for "dwd.0.warning3.level" has to be type "number" but received type "string"
dwd.0 | 2021-05-27 10:35:02.878 | info | State value to set for "dwd.0.warning3.type" has to be type "number" but received type "string"
dwd.0 | 2021-05-27 10:35:02.819 | info | State value to set for "dwd.0.numberofwarnings" has to be type "number" but received type "string"
dwd.0 | 2021-05-27 10:35:02.399 | info | starting. Version 2.7.5 in /opt/iobroker/node_modules/iobroker.dwd, node: v12.18.3, js-controller: 3.3.11

**Comment by GermanBluefox** [comment]
please test 2.7.6
