### ISSUE TITLE
different data type for dwd.0.warning.begin vs. dwd.0.warning[1..n].begin

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.dwd#91]
dwd.0.warning.begin is type: "number", all other warning begin objects are type "string".
In "/opt/iobroker/node_modules/iobroker.dwd/io-package.json" only "warning.begin" exists with object definition.

dwd: 2.7.6
JS-Controller: 3.3.14
NodeJS: 12.22.1

With 2.7.5 all begin objects were strings, but contains a unix timestamp, where number would be the proper type.

**Comment by GermanBluefox** [comment]
How exactly the warning looks like?

**Comment by Diginix** [comment]
No warnings so far. Just a hint, that it looks not "perfect" ;-)
Same objects should be of same type, I guess.

**Comment by Diginix** [comment]
Now that a real warning comes, it leads to an error:
real begin from XML: Di, 29. Jun, 20:00
object value: Sun Nov 15 53463 01:00:00 GMT+0100 (Mitteleuropäische Normalzeit)

real end from XML: Di, 29. Jun, 21:00
object value: Sat Dec 26 53463 17:00:00 GMT+0100 (Mitteleuropäische Normalzeit)

**Comment by mediaDS** [comment]
Same here. Both warnings show wrong dates.

**Comment by Apollon77** [comment]
Provide a full debug log please with infos hats wrong in your eyes based on this full log. Thank you

**Comment by Apollon77** [comment]
Looks all good, warning.begin and end should be numbers, rest string. Please delete the objects pot. and let them be recreated.
That begin/end contained ionvalid values is fixed on Github

**Comment by Diginix** [comment]
I will try the fixed version as soon as DWD has new warnings for my region.
And yes, number is the correct data type but why it is only for begin+end of the first warning?
All others dwd.0.warning1.begin, dwd.0.warning1.end, dwd.0.warning2.begin dwd.0.warning2.end ... has still string as type.

**Comment by Apollon77** [comment]
Also after you deleted all objects and let them being recreated?

**Comment by Diginix** [comment]
Ok, no, I haven't tested this yet. I'll let you know.
