### ISSUE TITLE
Keine DWD-Warnungen

### ISSUE THREAD

**Issue by Fritzelspitze** [ioBroker/ioBroker.dwd#92]
Ich habe bereits vor über einer Stunde eine DWD-Warnung auf mein Handy bekommen aber im ioBroker wird immernoch nichts angezeigt. Der Zeitplan in den Instanzen steht auf 5 Minuten.

**Comment by Apollon77** [comment]
Bitte Debug Log des Adapters posten

**Comment by Fritzelspitze** [comment]
![dwd](https://user-images.githubusercontent.com/82735748/123886308-77c56100-d94f-11eb-88b5-2e515b041749.PNG)


Ich sehe da was von Cottbus, Cottbus habe ich nicht als Region angegeben. Ich habe dort eine Stadt in NRW eingetragen, mehr nicht.

**Comment by Fritzelspitze** [comment]
Eine Neuinstallation hat übrigens nicht geholfen.

**Comment by Apollon77** [comment]
Bitte Log aus dem Logfile auf der Platte (/opt/iobroker/logs/... ... mit nem Screenshot kann niemand arbeiten und Admin schneidet lange Zeilen ab

**Comment by Fritzelspitze** [comment]
[log.txt](https://github.com/ioBroker/ioBroker.dwd/files/6739052/log.txt)
Bittesehr :)

**Comment by PrinzEisenherz1** [comment]
Hi Apollon, Ich habe das selbe Problem das im Heidekreis nichts mehr angezeigt wird obwohl Warnungen vorliegen.
![2021-06-30](https://user-images.githubusercontent.com/17569151/123998770-18f4fb80-d9d2-11eb-803d-7aa0a30aea24.png)
und hier mal das log wenn ich auf debug stelle
[iobroker.2021-06-30.txt](https://github.com/ioBroker/ioBroker.dwd/files/6742571/iobroker.2021-06-30.txt)

Gruß Johnny

**Comment by Apollon77** [comment]
@PrinzEisenherz1 Wie siehst die Konfig aus? Am besten screenshot adapterkonfig und auch object JSON von system.adapter.dwd.0

**Comment by Apollon77** [comment]
@PrinzEisenherz1 Ok, anders: GitHub version bitte nutzen und nochmal log posten. Habe jetzt geloggt wonach er sucht

**Comment by PrinzEisenherz1** [comment]
@Apollon77 Sorry für die späte Anwort. Ich hab die aktuelle vom git installiert und hier mal die log
[iobroker.2021-07-05.txt](https://github.com/ioBroker/ioBroker.dwd/files/6765175/iobroker.2021-07-05.txt)
Verhalten ist das gleiche wie auf dem Bild im oberen Beitrag. Komisch ist, das es jetzt 4-5 Tage wieder ging und gerade wieder nicht.

Gruß
Johnny

**Comment by Apollon77** [comment]
Tha, schau ins Log .. die gelogtten Daten sind die die abgeholt wurden ... Für "Heidekreis" steht da halt einfach nix drin. Also kann der Adapter nix finden. Wüsste daher nicht wie es am Adapter liegen soll :-)
